// Widget asset-catalog colors, derived from the brand palette in
// apps/mobile/src/theme.ts. colors.generated.cjs is generated by
// scripts/generate-widget-colors.mjs (run via pnpm surface:codegen) and
// drift-gated against theme.ts, so the widget target and the React Native
// app cannot fall out of sync. The require stays CJS-to-CJS, which
// @bacons/apple-targets reads cleanly at prebuild time.
const COLORS = require("./colors.generated.cjs");

/** @type {import('@bacons/apple-targets').ConfigFunction} */
module.exports = (config) => ({
  type: "widget",
  name: "MobileSurfacesWidget",
  icon: "../../assets/icon.png",
  deploymentTarget: "17.2",
  frameworks: ["ActivityKit", "AppIntents", "WidgetKit", "SwiftUI"],
  entitlements: {
    "com.apple.security.application-groups":
      config.ios?.entitlements?.["com.apple.security.application-groups"] ?? [],
  },
  colors: {
    $accent: COLORS.AccentColor,
    $widgetBackground: COLORS.WidgetBackground,
  },
});
