// AUTO-GENERATED by scripts/generate-surface-swift.mjs. DO NOT EDIT.
//
// Source of truth: packages/surface-contracts/src/schema.ts
//   liveSurfaceWidgetTimelineEntry, liveSurfaceControlValueProvider,
//   liveSurfaceLockAccessoryEntry, liveSurfaceStandbyEntry.
//
// These Codable structs decode the App Group snapshot payloads the host
// writes for the widget, control, lock-accessory, and StandBy surfaces. A
// field, type, JSON key, or optionality drift from the Zod projection-output
// schema makes JSONDecoder silently fail and the surface render placeholder
// data forever (MS036). Generating from Zod keeps the structs in lockstep.
//
// To change a field, edit the Zod schema and run:
//   pnpm surface:codegen --only=generate-surface-swift

import Foundation

struct MobileSurfacesWidgetSnapshot: Codable, Hashable {
  var schemaVersion: String
  var kind: String
  var snapshotId: String
  var surfaceId: String
  var state: String
  var family: String?
  var reloadPolicy: String?
  var headline: String
  var subhead: String
  var progress: Double
  var deepLink: String
}

struct MobileSurfacesControlSnapshot: Codable, Hashable {
  var schemaVersion: String
  var kind: String
  var snapshotId: String
  var surfaceId: String
  var controlKind: String
  var value: Bool?
  var intent: String?
  var label: String
  var deepLink: String
}

struct MobileSurfacesLockAccessorySnapshot: Codable, Hashable {
  var schemaVersion: String
  var kind: String
  var snapshotId: String
  var surfaceId: String
  var state: String
  var family: String
  var headline: String
  var shortText: String?
  var gaugeValue: Double?
  var deepLink: String
}

struct MobileSurfacesStandbySnapshot: Codable, Hashable {
  var schemaVersion: String
  var kind: String
  var snapshotId: String
  var surfaceId: String
  var state: String
  var presentation: String
  var tint: String?
  var headline: String
  var subhead: String
  var progress: Double
  var deepLink: String
}
