// Generated from data/traps.json by scripts/generate-trap-bindings.mjs.
// The catalog is the source of truth; do not edit this file by hand.
// Run pnpm surface:check (which calls --check) to verify drift; run
// node --experimental-strip-types scripts/generate-trap-bindings.mjs to
// regenerate after editing data/traps.json.

/**
 * Runtime view of a single trap catalog entry. Carries the fields a backend
 * operator needs to act on a logged error: human title, severity, the
 * symptom they're seeing, the fix, and a docsUrl pointing at the rendered
 * catalog. Other catalog fields (tags, enforcement script, since version)
 * stay out of the bundle — consult data/traps.json or the rendered CLAUDE.md
 * for the full record.
 */
export interface TrapBinding {
  readonly id: string;
  readonly title: string;
  readonly severity: "error" | "warning" | "info";
  readonly summary: string;
  readonly symptom: string;
  readonly fix: string;
  readonly docsUrl: string;
}

export const TRAP_ID_BY_ERROR_CLASS = {
  BadChannelIdError: "MS031",
  BadDateError: "MS032",
  BadDeviceTokenError: "MS014",
  BadExpirationDateError: "MS032",
  ChannelNotRegisteredError: "MS031",
  ExpiredProviderTokenError: "MS030",
  FeatureNotEnabledError: "MS034",
  ForbiddenError: "MS030",
  InvalidProviderTokenError: "MS030",
  MissingApnsConfigError: "MS028",
  MissingChannelIdError: "MS031",
  MissingTopicError: "MS035",
  PayloadTooLargeError: "MS011",
  TooManyRequestsError: "MS015",
  TopicDisallowedError: "MS018",
  UnregisteredError: "MS020",
} as const satisfies Record<string, `MS${string}`>;

export type TrapBoundErrorClassName = keyof typeof TRAP_ID_BY_ERROR_CLASS;

export const TRAP_BINDINGS = {
  MS011: {
    id: "MS011",
    title: "ActivityKit payload size ceiling (4 KB / 5 KB broadcast)",
    severity: "error",
    summary: "Per-activity Live Activity pushes are bounded at 4 KB; iOS 18 broadcast pushes at 5 KB.",
    symptom: "APNs returns 413 PayloadTooLarge, or accepts the payload but iOS silently drops the update. Long localized strings or accumulated morePartsCount details are common offenders.",
    fix: "Trim the payload. Per-activity payloads are bounded at 4 KB; broadcast payloads at 5 KB. Shorten secondaryText, lower morePartsCount, or split a state into two smaller pushes. Validate by sending the projection through toLiveActivityContentState and measuring.",
    docsUrl: "https://github.com/glendonC/mobile-surfaces/blob/main/CLAUDE.md#ms011-activitykit-payload-size-ceiling-4-kb-5-kb-broadcast",
  },
  MS014: {
    id: "MS014",
    title: "APNs token environment must match the build environment",
    severity: "error",
    summary: "Tokens minted by a development build cannot authenticate against the production APNs endpoint, and vice versa.",
    symptom: "APNs responds 400 BadDeviceToken. The token is valid; it just belongs to the other environment.",
    fix: "Use environment: 'development' for dev-client and expo run:ios builds, environment: 'production' only for TestFlight and App Store builds. Track which environment minted each token.",
    docsUrl: "https://github.com/glendonC/mobile-surfaces/blob/main/CLAUDE.md#ms014-apns-token-environment-must-match-the-build-environment",
  },
  MS015: {
    id: "MS015",
    title: "Push priority 5 vs 10 budget rules",
    severity: "warning",
    summary: "Live Activity priority 10 is for immediate user-visible updates and is heavily budgeted by iOS; sustained priority 10 sends are silently throttled.",
    symptom: "Updates land for the first few pushes then mysteriously stop arriving on the device. APNs returns 200; iOS still drops them. Logs show TooManyRequests bursts.",
    fix: "Default to priority 5 for Live Activity content-state updates. Reserve priority 10 for state transitions the user must see immediately (queued→active, completed).",
    docsUrl: "https://github.com/glendonC/mobile-surfaces/blob/main/CLAUDE.md#ms015-push-priority-5-vs-10-budget-rules",
  },
  MS018: {
    id: "MS018",
    title: "APNS_BUNDLE_ID must not include the .push-type.liveactivity suffix",
    severity: "error",
    summary: "The push SDK auto-appends .push-type.liveactivity to the apns-topic; passing it pre-suffixed produces a malformed topic header.",
    symptom: "APNs responds 400 TopicDisallowed even though your auth key is correctly enabled for the app. The topic header has the suffix doubled or in the wrong position.",
    fix: "Set APNS_BUNDLE_ID to the bare bundle id (e.g. com.example.mobilesurfaces). The SDK and scripts/send-apns.mjs both handle the suffix internally.",
    docsUrl: "https://github.com/glendonC/mobile-surfaces/blob/main/CLAUDE.md#ms018-apns-bundle-id-must-not-include-the-push-type-liveactivity-suffix",
  },
  MS020: {
    id: "MS020",
    title: "Per-activity and push-to-start tokens may rotate at any time",
    severity: "error",
    summary: "Both pushTokenUpdates and pushToStartTokenUpdates may emit fresh values at any moment (cold launch, system rotation, foreground transition).",
    symptom: "Backend send to a stored token returns 410 Unregistered or 400 BadDeviceToken on a previously-working device. The user did nothing wrong; the OS rotated the token.",
    fix: "Treat the latest event as authoritative. Re-store on every emission keyed by user/device id, and update the active record rather than appending.",
    docsUrl: "https://github.com/glendonC/mobile-surfaces/blob/main/CLAUDE.md#ms020-per-activity-and-push-to-start-tokens-may-rotate-at-any-time",
  },
  MS028: {
    id: "MS028",
    title: "APNs auth key environment variables must be set before sending",
    severity: "error",
    summary: "Both the SDK and scripts/send-apns.mjs require APNS_KEY_ID, APNS_TEAM_ID, APNS_KEY_PATH, and APNS_BUNDLE_ID.",
    symptom: "Throw at construction time (createPushClient) or at the first send. Often hidden inside a deployment whose env vars never made it into the runtime.",
    fix: "Verify each env var on startup. The SDK's createPushClient validates presence; reject fast if any are missing.",
    docsUrl: "https://github.com/glendonC/mobile-surfaces/blob/main/CLAUDE.md#ms028-apns-auth-key-environment-variables-must-be-set-before-sending",
  },
  MS030: {
    id: "MS030",
    title: "APNs provider token must be valid and current",
    severity: "error",
    summary: "APNs returns 403 with reason Forbidden, InvalidProviderToken, or ExpiredProviderToken when the auth-key JWT cannot be verified; each reason has a distinct operator response.",
    symptom: "All sends fail with 403. ForbiddenError means the auth key was revoked in the Apple Developer portal. InvalidProviderTokenError means the JWT is malformed or signed with the wrong key id / team id. ExpiredProviderTokenError means the JWT is older than 60 minutes (typically clock skew, since the SDK refreshes at 50 minutes).",
    fix: "ForbiddenError: mint a new auth key in the Apple Developer portal and update APNS_KEY_ID / APNS_KEY_PATH. InvalidProviderTokenError: verify APNS_KEY_ID matches the key file and APNS_TEAM_ID matches the developer account. ExpiredProviderTokenError: check system clock alignment against NTP; if the SDK is long-lived, confirm createPushClient is not being held past process restarts without re-minting.",
    docsUrl: "https://github.com/glendonC/mobile-surfaces/blob/main/CLAUDE.md#ms030-apns-provider-token-must-be-valid-and-current",
  },
  MS031: {
    id: "MS031",
    title: "Channel management failures (missing, malformed, or unregistered channel id)",
    severity: "error",
    summary: "Broadcast and channel-admin calls reject when the channel id is missing from the request, malformed on the wire, or refers to a channel that was never created in the target environment.",
    symptom: "Broadcast or channel management fails with 400 (missing or bad channel id) or 410 (not registered). Common root causes: the channel was created against the opposite APNs environment, or the id was URL-decoded, truncated, or otherwise mutated before being sent back.",
    fix: "MissingChannelId: pass channelId to broadcast() or deleteChannel(). BadChannelId: use the id returned by createChannel() verbatim with no URL-decoding or truncation. ChannelNotRegistered: channels are environment-scoped, so re-create the channel in the target environment or call listChannels() to confirm the id exists there.",
    docsUrl: "https://github.com/glendonC/mobile-surfaces/blob/main/CLAUDE.md#ms031-channel-management-failures-missing-malformed-or-unregistered-channel-id",
  },
  MS032: {
    id: "MS032",
    title: "Activity timestamp fields must be valid unix-seconds integers",
    severity: "error",
    summary: "APNs rejects Live Activity pushes whose date fields (staleDateSeconds, dismissalDateSeconds, apns-expiration) are not positive unix-seconds integers, and rejects broadcast sends to a no-storage channel that carry a nonzero apns-expiration.",
    symptom: "APNs returns 400 BadDate or 400 BadExpirationDate. The push payload looked valid locally but a date field was a millisecond timestamp, a negative number, or a non-integer; or apns-expiration was set on a no-storage broadcast channel.",
    fix: "Confirm every date field is a positive unix-seconds integer (not milliseconds, not Date.now()). For broadcast on a no-storage channel, apns-expiration must be 0; the SDK's broadcast() already enforces this.",
    docsUrl: "https://github.com/glendonC/mobile-surfaces/blob/main/CLAUDE.md#ms032-activity-timestamp-fields-must-be-valid-unix-seconds-integers",
  },
  MS034: {
    id: "MS034",
    title: "Broadcast capability must be enabled on the APNs auth key",
    severity: "error",
    summary: "iOS 18 broadcast pushes and channel-admin calls require the 'Broadcast to Live Activity' capability on the APNs auth key. The capability is per-key, not per-app, and is invisible until the first send fails.",
    symptom: "createChannel() or broadcast() fails with 403 FeatureNotEnabled. The auth key is otherwise valid and other push types succeed; only broadcast-related calls reject.",
    fix: "Enable broadcast in the Apple Developer portal under Certificates, Identifiers & Profiles > Keys > select the key > edit > tick 'Broadcast to Live Activity'. Save and retry; no client change is needed.",
    docsUrl: "https://github.com/glendonC/mobile-surfaces/blob/main/CLAUDE.md#ms034-broadcast-capability-must-be-enabled-on-the-apns-auth-key",
  },
  MS035: {
    id: "MS035",
    title: "apns-topic header missing or bundleId misconfigured",
    severity: "error",
    summary: "APNs requires an apns-topic header on every request; the SDK derives it from APNS_BUNDLE_ID and a missing or empty bundle id produces a malformed topic at send time.",
    symptom: "APNs returns 400 MissingTopic. The bundle id was unset or an empty string, so the SDK emitted only the .push-type.liveactivity suffix (or nothing) as the topic header.",
    fix: "Confirm APNS_BUNDLE_ID is set to the bare bundle identifier (e.g. com.example.app). Do not include the .push-type.liveactivity suffix; the SDK appends it internally. See MS018 for the inverse failure (suffix included by mistake).",
    docsUrl: "https://github.com/glendonC/mobile-surfaces/blob/main/CLAUDE.md#ms035-apns-topic-header-missing-or-bundleid-misconfigured",
  },
} as const satisfies Record<string, TrapBinding>;

export type BoundTrapId = keyof typeof TRAP_BINDINGS;

/**
 * Look up the trap id for a given error class name. Returns undefined for
 * classes that have no catalog entry (most SDK-self-correctness errors).
 */
export function trapIdForErrorClass(className: string): string | undefined {
  return (TRAP_ID_BY_ERROR_CLASS as Record<string, string>)[className];
}

/**
 * Look up a trap binding by id. Returns undefined when the id is not in the
 * runtime subset (the binding file only ships entries reachable through a
 * typed error class).
 */
export function findTrap(trapId: string): TrapBinding | undefined {
  return (TRAP_BINDINGS as Record<string, TrapBinding>)[trapId];
}

/**
 * Look up the trap binding for an error class name. Composes
 * trapIdForErrorClass with findTrap so log aggregators can stamp a single
 * `docsUrl` per error without juggling two maps.
 */
export function findTrapByErrorClass(className: string): TrapBinding | undefined {
  const id = trapIdForErrorClass(className);
  return id ? findTrap(id) : undefined;
}

/**
 * Resolve the docs URL for an error class, or undefined when the class has
 * no catalog binding. Equivalent to findTrapByErrorClass(name)?.docsUrl;
 * exposed as a getter so the hot path on ApnsError can skip the object spread.
 */
export function docsUrlForErrorClass(className: string): string | undefined {
  return findTrapByErrorClass(className)?.docsUrl;
}
