// Generated from data/traps.json by scripts/generate-trap-bindings.mjs.
// Each binding pairs a typed APNs error class name with the trap id it
// surfaces and the docs path that explains it. The catalog is the source of
// truth; do not edit this file by hand. Run pnpm surface:check (which calls
// --check) to verify drift; run node --experimental-strip-types
// scripts/generate-trap-bindings.mjs to regenerate after editing
// data/traps.json.

export const TRAP_ID_BY_ERROR_CLASS = {
  BadDeviceTokenError: "MS014",
  ExpiredProviderTokenError: "MS030",
  ForbiddenError: "MS030",
  InvalidProviderTokenError: "MS030",
  MissingApnsConfigError: "MS028",
  PayloadTooLargeError: "MS011",
  TooManyRequestsError: "MS015",
  TopicDisallowedError: "MS018",
  UnregisteredError: "MS020",
} as const satisfies Record<string, `MS${string}`>;

export type TrapBoundErrorClassName = keyof typeof TRAP_ID_BY_ERROR_CLASS;

// Catalog-derived docs path for each trap-bound error class. Repo-relative
// (e.g. "docs/push.md#error-responses"); resolve to a full URL via
// docsUrlForErrorClass().
export const DOCS_PATH_BY_ERROR_CLASS = {
  BadDeviceTokenError: "docs/push.md#error-responses",
  ExpiredProviderTokenError: "docs/push.md#error-responses",
  ForbiddenError: "docs/push.md#error-responses",
  InvalidProviderTokenError: "docs/push.md#error-responses",
  MissingApnsConfigError: "docs/push.md#sdk-reference",
  PayloadTooLargeError: "docs/push.md#error-responses",
  TooManyRequestsError: "docs/push.md#error-responses",
  TopicDisallowedError: "docs/push.md#error-responses",
  UnregisteredError: "docs/push.md#token-taxonomy",
} as const satisfies Record<string, string>;

// Default base for docs URLs. Overridable via MOBILE_SURFACES_DOCS_BASE for
// forks or for pointing at a published site. The trailing slash matters; the
// catalog docs paths are appended verbatim.
export const DEFAULT_DOCS_BASE_URL =
  "https://github.com/glendonC/mobile-surfaces/blob/main/";

// Fallback when an error class has no catalog binding. Lands the reader on
// the canonical error-responses table.
export const FALLBACK_DOCS_PATH = "docs/push.md#error-responses";

function resolveDocsBase(): string {
  const override = (globalThis as { process?: { env?: Record<string, string | undefined> } })
    .process?.env?.MOBILE_SURFACES_DOCS_BASE;
  if (override && override.length > 0) {
    return override.endsWith("/") ? override : override + "/";
  }
  return DEFAULT_DOCS_BASE_URL;
}

/**
 * Look up the trap id for a given error class name. Returns undefined for
 * classes that have no catalog entry (most SDK-self-correctness errors).
 * Consumers should treat the result as opaque metadata for log aggregation
 * or doc-link rendering; the trap catalog is the canonical source of fix
 * instructions.
 */
export function trapIdForErrorClass(className: string): string | undefined {
  return (TRAP_ID_BY_ERROR_CLASS as Record<string, string>)[className];
}

/**
 * Resolve a full docs URL for the given error class name. Returns the
 * catalog-derived URL for trap-bound classes, the fallback error-responses
 * anchor for unbound classes (e.g. UnknownApnsError). Always returns a URL —
 * agents can always WebFetch the result for context. Overridable globally via
 * the MOBILE_SURFACES_DOCS_BASE env var.
 */
export function docsUrlForErrorClass(className: string): string {
  const base = resolveDocsBase();
  const path =
    (DOCS_PATH_BY_ERROR_CLASS as Record<string, string>)[className] ??
    FALLBACK_DOCS_PATH;
  return base + path;
}
