// AUTO-GENERATED by scripts/codegen-activity-attributes.mjs. DO NOT EDIT.
//
// Source of truth: packages/surface-contracts/src/schema.ts
//   - liveSurfaceActivityContentState defines the ContentState fields below.
//   - liveSurfaceStage defines the Stage enum cases below.
//
// MUST stay byte-identical across the Expo module and widget target:
//   packages/live-activity/ios/MobileSurfacesActivityAttributes.swift
//   apps/mobile/targets/widget/MobileSurfacesActivityAttributes.swift
//
// ActivityKit binds the type used in `Activity<T>.request` (main app) to the
// type used in `ActivityConfiguration(for: T.self)` (widget extension) by
// matching ContentState/Attributes shape. The two definitions live in
// different Swift modules at compile time but must serialize identically.
//
// To change ContentState fields or Stage cases, edit the Zod schema and run:
//   pnpm codegen:activity-attributes

import ActivityKit

struct MobileSurfacesActivityAttributes: ActivityAttributes, Sendable {
  public struct ContentState: Codable, Hashable, Sendable {
    var headline: String
    var subhead: String
    var progress: Double
    var stage: Stage
  }

  enum Stage: String, Codable, Hashable, Sendable {
    case prompted
    case inProgress
    case completing
  }

  var surfaceId: String
  var modeLabel: String
}
