// AUTO-GENERATED by scripts/generate-surface-swift.mjs. DO NOT EDIT.
//
// Source of truth: packages/surface-contracts/src/schema.ts
//   liveSurfaceNotificationContentEntry.
//
// The notification-content extension decodes this Codable sidecar from the
// wire payload's `liveSurface` key. A field, type, JSON key, or optionality
// drift from the Zod projection-output schema makes JSONDecoder silently
// fail and the extension render the default system chrome instead of the
// surface-aware view (MS036).
//
// To change a field, edit the Zod schema and run:
//   pnpm surface:codegen --only=generate-surface-swift

import Foundation

struct MobileSurfacesNotificationContentEntry: Codable, Hashable {
  let schemaVersion: String
  let kind: String
  let snapshotId: String
  let surfaceId: String
  let state: String
  let deepLink: String
  let category: String?
}
