// End-to-end tests for scripts/codegen-activity-attributes.mjs.
//
// The codegen reads the real Zod schemas from
// packages/surface-contracts/src/schema.ts and writes Swift to two paths.
// Tests run it as a subprocess so they cover the exact code path CI uses
// (--print, --check, default-write). Each test stages a fresh tmp workspace
// with the two target subdirs; the codegen resolves the schema through the
// real repo via the path it imports, so a partial tmp workspace is enough.
//
// Assertions:
//   1. --print emits Swift that contains the four ContentState fields, the
//      three Stage cases, and the outer Attributes metadata.
//   2. Default-write produces byte-identical output across both paths.
//   3. --check on a fresh workspace fails (no files written yet); on a
//      workspace populated by a default-write run, --check passes.
//   4. --check on a workspace where one file was hand-edited reports drift
//      on that specific path.
//   5. --check on a workspace where both files were hand-edited identically
//      still fails — the codegen output is the source of truth, not
//      cross-file byte-identity.

import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");
const SCRIPT = join(REPO_ROOT, "scripts", "codegen-activity-attributes.mjs");

const MODULE_REL = "packages/live-activity/ios/MobileSurfacesActivityAttributes.swift";
const WIDGET_REL = "apps/mobile/targets/widget/MobileSurfacesActivityAttributes.swift";

function makeWorkspace() {
  const dir = mkdtempSync(join(tmpdir(), "ms-codegen-attrs-"));
  mkdirSync(join(dir, "packages", "live-activity", "ios"), { recursive: true });
  mkdirSync(join(dir, "apps", "mobile", "targets", "widget"), { recursive: true });
  return { dir, cleanup: () => rmSync(dir, { recursive: true, force: true }) };
}

function run(cwd, ...args) {
  return spawnSync(
    "node",
    [
      "--experimental-strip-types",
      "--no-warnings=ExperimentalWarning",
      SCRIPT,
      ...args,
    ],
    { cwd, encoding: "utf8" },
  );
}

test("--print emits the ContentState fields, Stage cases, and outer Attributes", () => {
  const ws = makeWorkspace();
  try {
    const result = run(ws.dir, "--print");
    assert.equal(result.status, 0, result.stderr);
    const out = result.stdout;
    // ContentState fields (from liveSurfaceActivityContentState):
    assert.match(out, /var headline: String\b/);
    assert.match(out, /var subhead: String\b/);
    assert.match(out, /var progress: Double\b/);
    assert.match(out, /var stage: Stage\b/);
    // Stage cases (from liveSurfaceStage):
    assert.match(out, /case prompted\b/);
    assert.match(out, /case inProgress\b/);
    assert.match(out, /case completing\b/);
    // Outer Attributes metadata stays in the fixed template:
    assert.match(out, /var surfaceId: String\b/);
    assert.match(out, /var modeLabel: String\b/);
    // Auto-generated banner makes it clear nobody should hand-edit:
    assert.match(out, /AUTO-GENERATED by scripts\/codegen-activity-attributes\.mjs/);
    // No files written in --print mode:
    assert.equal(existsSync(join(ws.dir, MODULE_REL)), false);
    assert.equal(existsSync(join(ws.dir, WIDGET_REL)), false);
  } finally {
    ws.cleanup();
  }
});

test("default write produces byte-identical output across both target paths", () => {
  const ws = makeWorkspace();
  try {
    const result = run(ws.dir);
    assert.equal(result.status, 0, result.stderr);
    const modulePath = join(ws.dir, MODULE_REL);
    const widgetPath = join(ws.dir, WIDGET_REL);
    assert.equal(existsSync(modulePath), true);
    assert.equal(existsSync(widgetPath), true);
    const moduleContent = readFileSync(modulePath, "utf8");
    const widgetContent = readFileSync(widgetPath, "utf8");
    assert.equal(moduleContent, widgetContent, "module and widget Swift differ");
  } finally {
    ws.cleanup();
  }
});

test("--check on an empty workspace reports drift (no committed files yet)", () => {
  const ws = makeWorkspace();
  try {
    const result = run(ws.dir, "--check");
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /out of sync with the Zod source of truth/);
  } finally {
    ws.cleanup();
  }
});

test("--check after default-write passes", () => {
  const ws = makeWorkspace();
  try {
    const writeResult = run(ws.dir);
    assert.equal(writeResult.status, 0, writeResult.stderr);
    const checkResult = run(ws.dir, "--check");
    assert.equal(checkResult.status, 0, checkResult.stderr);
    assert.match(checkResult.stdout, /in sync with packages\/surface-contracts/);
  } finally {
    ws.cleanup();
  }
});

test("--check reports drift on a hand-edited file even if the other path matches codegen", () => {
  const ws = makeWorkspace();
  try {
    // Populate both files with the canonical codegen output.
    const writeResult = run(ws.dir);
    assert.equal(writeResult.status, 0, writeResult.stderr);
    // Hand-edit the widget file: add a stray comment line. Byte-identity
    // across files would still hold if we changed both; we only change one
    // here to verify per-file drift reporting.
    const widgetPath = join(ws.dir, WIDGET_REL);
    writeFileSync(widgetPath, readFileSync(widgetPath, "utf8") + "// hand-edit\n");
    const checkResult = run(ws.dir, "--check");
    assert.notEqual(checkResult.status, 0);
    assert.match(checkResult.stderr, /apps\/mobile\/targets\/widget\/MobileSurfacesActivityAttributes\.swift is out of sync/);
    assert.doesNotMatch(
      checkResult.stderr,
      /packages\/live-activity\/ios\/MobileSurfacesActivityAttributes\.swift is out of sync/,
    );
  } finally {
    ws.cleanup();
  }
});

test("--check fails when both files are hand-edited identically but diverge from codegen", () => {
  const ws = makeWorkspace();
  try {
    const writeResult = run(ws.dir);
    assert.equal(writeResult.status, 0, writeResult.stderr);
    const modulePath = join(ws.dir, MODULE_REL);
    const widgetPath = join(ws.dir, WIDGET_REL);
    // Mutate both files identically: rename a field. Byte-identity across
    // files holds (a naive byte-identity-only gate would pass), but the
    // codegen output is the source of truth so --check must catch the
    // structural divergence from the Zod schema.
    const tampered = readFileSync(modulePath, "utf8").replace(
      /var headline: String/,
      "var headline: String?",
    );
    writeFileSync(modulePath, tampered);
    writeFileSync(widgetPath, tampered);
    const checkResult = run(ws.dir, "--check");
    assert.notEqual(checkResult.status, 0);
    assert.match(checkResult.stderr, /out of sync with the Zod source of truth/);
  } finally {
    ws.cleanup();
  }
});

test("default write is idempotent (running twice produces the same content)", () => {
  const ws = makeWorkspace();
  try {
    const first = run(ws.dir);
    assert.equal(first.status, 0, first.stderr);
    const after1 = readFileSync(join(ws.dir, MODULE_REL), "utf8");
    const second = run(ws.dir);
    assert.equal(second.status, 0, second.stderr);
    const after2 = readFileSync(join(ws.dir, MODULE_REL), "utf8");
    assert.equal(after1, after2, "second write changed the output");
  } finally {
    ws.cleanup();
  }
});
