// End-to-end tests for scripts/generate-surface-swift.mjs.
//
// The codegen reads the real Zod schemas from
// packages/surface-contracts/src/schema.ts and writes Swift to four paths:
// the two byte-identical MobileSurfacesActivityAttributes.swift copies, the
// MobileSurfacesSurfaceSnapshots.swift file (four App-Group decoder structs),
// and the MobileSurfacesNotificationContentEntry.swift sidecar.
//
// Tests run it as a subprocess so they cover the exact code path CI uses
// (--print, --check, default-write). Each test stages a fresh tmp workspace
// with the four target subdirs; the codegen resolves the schema through the
// real repo via the path it imports, so a partial tmp workspace is enough.
//
// This file is also the MS036 regression suite: the surface-snapshot structs
// are generated, so "the struct matches Zod" is guaranteed by construction
// and the remaining failure mode — a committed file drifting from codegen —
// is what --check (and these tests) cover.

import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");
const SCRIPT = join(REPO_ROOT, "scripts", "generate-surface-swift.mjs");

const MODULE_REL = "packages/live-activity/ios/MobileSurfacesActivityAttributes.swift";
const WIDGET_REL = "apps/mobile/targets/widget/MobileSurfacesActivityAttributes.swift";
const SNAPSHOTS_REL = "apps/mobile/targets/_shared/MobileSurfacesSurfaceSnapshots.swift";
const NOTIFICATION_REL =
  "apps/mobile/targets/notification-content/MobileSurfacesNotificationContentEntry.swift";
const ALL_REL = [MODULE_REL, WIDGET_REL, SNAPSHOTS_REL, NOTIFICATION_REL];

function makeWorkspace() {
  const dir = mkdtempSync(join(tmpdir(), "ms-codegen-swift-"));
  for (const rel of ALL_REL) {
    mkdirSync(join(dir, dirname(rel)), { recursive: true });
  }
  return { dir, cleanup: () => rmSync(dir, { recursive: true, force: true }) };
}

function run(cwd, ...args) {
  return spawnSync(
    "node",
    [
      "--experimental-strip-types",
      "--no-warnings=ExperimentalWarning",
      SCRIPT,
      ...args,
    ],
    { cwd, encoding: "utf8" },
  );
}

test("--print emits the ActivityAttributes, surface-snapshot, and notification outputs", () => {
  const ws = makeWorkspace();
  try {
    const result = run(ws.dir, "--print");
    assert.equal(result.status, 0, result.stderr);
    const out = result.stdout;
    // ActivityKit ContentState fields + Stage cases + outer Attributes:
    assert.match(out, /var headline: String\b/);
    assert.match(out, /var stage: Stage\b/);
    assert.match(out, /case prompted\b/);
    assert.match(out, /var surfaceId: String\b/);
    assert.match(out, /var modeLabel: String\b/);
    // The four surface-snapshot structs:
    assert.match(out, /struct MobileSurfacesWidgetSnapshot: Codable, Hashable/);
    assert.match(out, /struct MobileSurfacesControlSnapshot: Codable, Hashable/);
    assert.match(out, /struct MobileSurfacesLockAccessorySnapshot: Codable, Hashable/);
    assert.match(out, /struct MobileSurfacesStandbySnapshot: Codable, Hashable/);
    // The notification-content sidecar, declared with `let` fields:
    assert.match(out, /struct MobileSurfacesNotificationContentEntry: Codable, Hashable/);
    assert.match(out, /let schemaVersion: String\b/);
    // Auto-generated banner names the current script:
    assert.match(out, /AUTO-GENERATED by scripts\/generate-surface-swift\.mjs/);
    // No files written in --print mode:
    for (const rel of ALL_REL) {
      assert.equal(existsSync(join(ws.dir, rel)), false);
    }
  } finally {
    ws.cleanup();
  }
});

test("default write produces all four files; the two ActivityAttributes paths are byte-identical", () => {
  const ws = makeWorkspace();
  try {
    const result = run(ws.dir);
    assert.equal(result.status, 0, result.stderr);
    for (const rel of ALL_REL) {
      assert.equal(existsSync(join(ws.dir, rel)), true, `${rel} not written`);
    }
    const moduleContent = readFileSync(join(ws.dir, MODULE_REL), "utf8");
    const widgetContent = readFileSync(join(ws.dir, WIDGET_REL), "utf8");
    assert.equal(moduleContent, widgetContent, "module and widget Swift differ");
  } finally {
    ws.cleanup();
  }
});

test("--check on an empty workspace reports drift (no committed files yet)", () => {
  const ws = makeWorkspace();
  try {
    const result = run(ws.dir, "--check");
    assert.notEqual(result.status, 0);
    assert.match(result.stdout, /out of sync with the Zod source of truth/);
  } finally {
    ws.cleanup();
  }
});

test("--check after default-write passes", () => {
  const ws = makeWorkspace();
  try {
    const writeResult = run(ws.dir);
    assert.equal(writeResult.status, 0, writeResult.stderr);
    const checkResult = run(ws.dir, "--check");
    assert.equal(checkResult.status, 0, checkResult.stderr);
  } finally {
    ws.cleanup();
  }
});

test("--check reports drift on a hand-edited surface-snapshots file", () => {
  const ws = makeWorkspace();
  try {
    const writeResult = run(ws.dir);
    assert.equal(writeResult.status, 0, writeResult.stderr);
    const snapshotsPath = join(ws.dir, SNAPSHOTS_REL);
    writeFileSync(snapshotsPath, readFileSync(snapshotsPath, "utf8") + "// hand-edit\n");
    const checkResult = run(ws.dir, "--check");
    assert.notEqual(checkResult.status, 0);
    assert.match(checkResult.stdout, /surface snapshot structs/);
  } finally {
    ws.cleanup();
  }
});

test("--check --json emits a DiagnosticReport with MS036 bound to the surface targets", () => {
  const ws = makeWorkspace();
  try {
    const writeResult = run(ws.dir);
    assert.equal(writeResult.status, 0, writeResult.stderr);
    const checkResult = run(ws.dir, "--check", "--json");
    assert.equal(checkResult.status, 0, checkResult.stderr);
    const report = JSON.parse(checkResult.stdout.trim());
    assert.equal(report.tool, "generate-surface-swift");
    assert.equal(report.status, "ok");
    const byId = Object.fromEntries(report.checks.map((c) => [c.id, c]));
    // The two surface targets carry MS036; the ActivityAttributes target
    // does not (MS002/MS003/MS004 live on check-activity-attributes.mjs).
    assert.equal(byId["surface-snapshots-sync"].trapId, "MS036");
    assert.equal(byId["notification-content-entry-sync"].trapId, "MS036");
    assert.equal(byId["activity-attributes-sync"].trapId, undefined);
  } finally {
    ws.cleanup();
  }
});

test("default write is idempotent (running twice produces the same content)", () => {
  const ws = makeWorkspace();
  try {
    assert.equal(run(ws.dir).status, 0);
    const first = ALL_REL.map((rel) => readFileSync(join(ws.dir, rel), "utf8"));
    assert.equal(run(ws.dir).status, 0);
    const second = ALL_REL.map((rel) => readFileSync(join(ws.dir, rel), "utf8"));
    assert.deepEqual(second, first, "second write changed the output");
  } finally {
    ws.cleanup();
  }
});
