#!/usr/bin/env node
// Interactive wizard to wire APNs credentials into the repo. Pairs with the
// Phase 2 diagnose bundle: MS028 detects when push is missing env vars; this
// command writes them. End-to-end flow:
//
//   1. Prompt for .p8 path, key id, team id, bundle id, environment.
//   2. Validate inputs (PEM markers, regex shapes, bundle-id constraints).
//   3. Mint a JWT and ping APNs sandbox with a bogus device token. Apple
//      returns 400 BadDeviceToken when creds are valid (the bogus token is
//      the failure, not auth) — that's our "creds work" signal. 403
//      InvalidProviderToken means the JWT was rejected (bad keyId/teamId/.p8).
//   4. Write a 600-mode .env with the resolved keys.
//
// Inputs validate against the same regexes the create-mobile-surfaces CLI
// uses, plus the MS018 constraint that APNS_BUNDLE_ID must NOT include the
// .push-type.liveactivity suffix (the SDK and send-apns.mjs append it
// internally). Validation step is skippable via --skip-validate for offline
// machines or paranoid users.

import fs from "node:fs";
import http2 from "node:http2";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { mintApnsJwt } from "./lib/jwt.mjs";
import { askChoice, askText, askYesNo, isCancelled } from "./lib/prompts.mjs";
import { redactHomePath, redactTokenLike } from "./lib/redact.mjs";
import { buildReport, emitDiagnosticReport } from "./lib/diagnostics.mjs";
import {
  banner,
  bold,
  cyan,
  dim,
  green,
  hyperlink,
  yellow,
} from "./lib/style.mjs";

const TOOL = "setup-apns";

// --- Pure helpers (exported for tests) -----------------------------------

export function expandHome(p) {
  if (!p) return p;
  if (p === "~") return os.homedir();
  if (p.startsWith("~/")) return path.join(os.homedir(), p.slice(2));
  return p;
}

export function validateKeyId(value) {
  if (!value) return "Key ID is required.";
  if (!/^[A-Z0-9]{10}$/.test(value)) {
    return "APNs Key IDs are exactly 10 uppercase letters and digits (e.g. ABCD1234EF).";
  }
  return null;
}

export function validateTeamId(value) {
  if (!value) return "Team ID is required.";
  if (!/^[A-Z0-9]{10}$/.test(value)) {
    return "Apple Team IDs are exactly 10 uppercase letters and digits.";
  }
  return null;
}

export function validateBundleId(value) {
  if (!value) return "Bundle ID is required.";
  if (/\.push-type\.liveactivity$/i.test(value)) {
    return "Drop the .push-type.liveactivity suffix — the SDK appends it (MS018).";
  }
  if (!/^[A-Za-z][A-Za-z0-9-]*(\.[A-Za-z0-9-]+){1,}$/.test(value)) {
    return "Should look like com.acme.myapp — at least two reverse-DNS segments.";
  }
  return null;
}

export function validateP8Path(rawPath) {
  if (!rawPath) return "Path to .p8 file is required.";
  const expanded = expandHome(rawPath);
  const absolute = path.isAbsolute(expanded)
    ? expanded
    : path.resolve(process.cwd(), expanded);
  if (!fs.existsSync(absolute)) {
    return `No file at ${redactHomePath(absolute)}. Check the path and try again.`;
  }
  let contents;
  try {
    contents = fs.readFileSync(absolute, "utf8");
  } catch (err) {
    return `Could not read ${redactHomePath(absolute)}: ${err.message}`;
  }
  if (
    !/-----BEGIN (EC )?PRIVATE KEY-----/.test(contents) ||
    !/-----END (EC )?PRIVATE KEY-----/.test(contents)
  ) {
    return `${redactHomePath(absolute)} doesn't look like a .p8 — missing PEM BEGIN/END PRIVATE KEY markers.`;
  }
  return null;
}

// Resolve a user-provided path to an absolute one (with ~ expansion).
// Separate from validateP8Path so we don't re-validate after the prompt.
export function resolveKeyPath(rawPath) {
  const expanded = expandHome(rawPath);
  return path.isAbsolute(expanded)
    ? expanded
    : path.resolve(process.cwd(), expanded);
}

const ENV_KEYS_ORDER = [
  "APNS_KEY_PATH",
  "APNS_KEY_ID",
  "APNS_TEAM_ID",
  "APNS_BUNDLE_ID",
  "APNS_ENV",
];

// Serialize the .env contents. Quoting policy: always wrap values in double
// quotes so paths with spaces survive a manual `source .env`. Values may
// not contain a literal " or $ — APNs ids and bundle ids never do.
export function serializeEnv(values) {
  const lines = [
    "# Generated by `pnpm surface:setup-apns`. Re-run to regenerate.",
    "# Do not commit this file — `.env` is gitignored.",
  ];
  for (const key of ENV_KEYS_ORDER) {
    const v = values[key];
    if (v === undefined || v === null || v === "") continue;
    lines.push(`${key}="${v}"`);
  }
  return lines.join("\n") + "\n";
}

// --- HTTP/2 credential probe --------------------------------------------

function originForEnv(envName) {
  return envName === "production"
    ? "https://api.push.apple.com:443"
    : "https://api.development.push.apple.com:443";
}

/**
 * Send a single request to APNs with a bogus device token to learn whether
 * the JWT was accepted. Returns {ok, status, reason} where ok=true means
 * the JWT authenticated successfully (regardless of token validity).
 */
export async function probeCredentials({
  keyPem,
  keyId,
  teamId,
  bundleId,
  envName,
  timeoutMs = 8000,
}) {
  const jwt = mintApnsJwt({ keyPem, keyId, teamId });
  const origin = originForEnv(envName);
  const apnsTopic = `${bundleId}.push-type.liveactivity`;
  const bogusToken = "0".repeat(64);
  const body = JSON.stringify({ aps: { "content-state": {}, event: "update" } });

  return new Promise((resolve) => {
    const session = http2.connect(origin);
    let resolved = false;
    const finish = (result) => {
      if (resolved) return;
      resolved = true;
      try {
        session.close();
      } catch {
        // ignore
      }
      resolve(result);
    };

    const timer = setTimeout(() => {
      finish({
        ok: false,
        status: 0,
        reason: `Timed out after ${timeoutMs}ms reaching ${origin}.`,
      });
    }, timeoutMs);

    session.on("error", (err) => {
      clearTimeout(timer);
      finish({ ok: false, status: 0, reason: err.message });
    });

    const req = session.request({
      ":method": "POST",
      ":path": `/3/device/${bogusToken}`,
      "apns-topic": apnsTopic,
      "apns-push-type": "liveactivity",
      authorization: `bearer ${jwt}`,
      "content-type": "application/json",
      "content-length": Buffer.byteLength(body),
    });

    let status = 0;
    let respBody = "";
    req.on("response", (headers) => {
      status = Number(headers[":status"]);
    });
    req.setEncoding("utf8");
    req.on("data", (chunk) => {
      respBody += chunk;
    });
    req.on("end", () => {
      clearTimeout(timer);
      let reason = "";
      try {
        const parsed = JSON.parse(respBody);
        reason = parsed.reason ?? "";
      } catch {
        reason = respBody.trim();
      }
      // Good-creds outcome: APNs accepted the JWT and rejected our bogus
      // token. Any 4xx that names the token (BadDeviceToken, DeviceTokenNotForTopic)
      // means auth worked — that's what we wanted to learn.
      const goodReasons = new Set([
        "BadDeviceToken",
        "DeviceTokenNotForTopic",
      ]);
      if (goodReasons.has(reason)) {
        finish({ ok: true, status, reason });
        return;
      }
      finish({ ok: false, status, reason: reason || `HTTP ${status}` });
    });
    req.on("error", (err) => {
      clearTimeout(timer);
      finish({ ok: false, status: 0, reason: err.message });
    });
    req.write(body);
    req.end();
  });
}

// --- File output --------------------------------------------------------

function repoRoot() {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, "..");
}

function ensureEnvGitignored(root) {
  const giPath = path.join(root, ".gitignore");
  if (!fs.existsSync(giPath)) return false;
  const contents = fs.readFileSync(giPath, "utf8");
  return /^\.env\b/m.test(contents) || /^\/\.env\b/m.test(contents);
}

// --- Main flow ----------------------------------------------------------

const HELP = `pnpm surface:setup-apns

Wire APNs credentials into the repo so push commands (mobile:push:sim,
mobile:push:device:liveactivity, send-apns.mjs) can authenticate without
the user manually exporting env vars.

Options:
  --skip-validate   Don't ping APNs to verify credentials.
  --no-write        Print the .env contents instead of writing.
  --json            Emit a DiagnosticReport instead of normal output.
  --help            Show this message.
`;

function parseCliArgs(argv) {
  return parseArgs({
    args: argv,
    options: {
      "skip-validate": { type: "boolean", default: false },
      "no-write": { type: "boolean", default: false },
      json: { type: "boolean", default: false },
      help: { type: "boolean", default: false },
    },
    allowPositionals: false,
  });
}

const APNS_KEYS_URL = "https://developer.apple.com/account/resources/authkeys/list";

// One-time pre-flight: tell the user what they need before we start
// asking for it. Without this, the first prompt drops a stranger into
// "give me a .p8 path" with no context. Skipped when --json is set so
// scripted use isn't polluted with prose.
function printIntro() {
  const lines = [
    "",
    banner("APNs setup"),
    "",
    "Wires APNs credentials so a backend can push to your Live Activity.",
    `${dim("Demo mode (Start/Update/End, widget, control) already works without push.")}`,
    "",
    bold("You'll need three things"),
    `  ${green("•")} An Apple Developer account.`,
    `  ${green("•")} A ${bold(".p8 APNs auth key")}: ${hyperlink("developer.apple.com → Keys → +", APNS_KEYS_URL)}.`,
    `    ${dim("Apple lets you download the file once — save it somewhere safe.")}`,
    `  ${green("•")} Your 10-character ${bold("Team ID")} and ${bold("Key ID")} ${dim("(both shown on the Keys page)")}.`,
    "",
    bold("Not sure how?") +
      " " +
      dim("Paste the line below to your AI assistant (Claude, ChatGPT, Cursor):"),
    "  " +
      cyan(
        `"I need to create an APNs auth key (.p8) on developer.apple.com to set up iOS push notifications. Walk me through it step by step."`,
      ),
    "  " + dim("Then come back here once you have the .p8 file downloaded."),
    "",
    `${yellow("⚑")} ${dim("Don't have these yet? Press Ctrl-C — the harness works without them.")}`,
    dim(`Re-run anytime with: ${bold("pnpm surface:setup-apns")}`),
    "",
  ];
  process.stdout.write(lines.join("\n") + "\n");
}

async function runWizard({ skipValidate, noWrite, json }) {
  const checks = [];
  const note = (status, summary, extra = {}) => {
    checks.push({ id: extra.id ?? `step-${checks.length + 1}`, status, summary, ...extra });
  };

  if (!json) printIntro();

  // --- Inputs ---
  // No default path — the user's .p8 lives wherever they downloaded it
  // (most browsers drop it in ~/Downloads as AuthKey_<keyid>.p8). A made-up
  // default path was the wrong help; the location hint goes in the prompt.
  const keyPathRaw = await askText({
    message: "Path to your .p8 file (e.g. ~/Downloads/AuthKey_ABCD1234EF.p8)",
    validate: validateP8Path,
  });
  if (isCancelled(keyPathRaw)) return { cancelled: true, checks };
  const keyPath = resolveKeyPath(keyPathRaw);

  const keyId = await askText({
    message: "APNs Key ID (10 chars, e.g. ABCD1234EF)",
    validate: validateKeyId,
  });
  if (isCancelled(keyId)) return { cancelled: true, checks };

  const teamId = await askText({
    message: "Apple Team ID (10 chars)",
    validate: validateTeamId,
  });
  if (isCancelled(teamId)) return { cancelled: true, checks };

  const bundleId = await askText({
    message: "Bundle ID (without the .push-type.liveactivity suffix)",
    validate: validateBundleId,
  });
  if (isCancelled(bundleId)) return { cancelled: true, checks };

  const envName = await askChoice({
    message: "Which APNs environment?",
    options: [
      { value: "development", label: "development (sandbox — for dev builds, Expo Go, simulator)" },
      { value: "production", label: "production (TestFlight, App Store)" },
    ],
    defaultValue: "development",
  });
  if (isCancelled(envName)) return { cancelled: true, checks };

  // --- Validation ---
  if (!skipValidate) {
    process.stdout.write(`\nPinging ${envName} APNs to verify credentials…\n`);
    const keyPem = fs.readFileSync(keyPath, "utf8");
    const probe = await probeCredentials({ keyPem, keyId, teamId, bundleId, envName });
    if (probe.ok) {
      process.stdout.write(`  ✓ Credentials valid (${probe.reason}).\n`);
      note("ok", `Credentials accepted by ${envName} APNs.`, {
        id: "credentials-valid",
        detail: { message: probe.reason },
      });
    } else {
      process.stdout.write(`  ✗ Validation failed: ${probe.reason}\n`);
      note("fail", `APNs rejected credentials: ${probe.reason}`, {
        id: "credentials-valid",
        detail: { message: `HTTP ${probe.status}: ${probe.reason}` },
        trapId:
          probe.reason === "InvalidProviderToken" || probe.reason === "ExpiredProviderToken"
            ? "MS028"
            : undefined,
      });
      return { aborted: true, checks };
    }
  } else {
    note("skip", "Skipped APNs credential validation (--skip-validate).", {
      id: "credentials-valid",
    });
  }

  // --- Write .env ---
  const root = repoRoot();
  const envPath = path.join(root, ".env");
  const values = {
    APNS_KEY_PATH: keyPath,
    APNS_KEY_ID: keyId,
    APNS_TEAM_ID: teamId,
    APNS_BUNDLE_ID: bundleId,
    APNS_ENV: envName,
  };
  const contents = serializeEnv(values);

  if (noWrite) {
    process.stdout.write(`\nWould write ${redactHomePath(envPath)}:\n${contents}\n`);
    note("ok", "Resolved .env contents (not written; --no-write).", {
      id: "env-written",
    });
    return { wrote: false, contents, envPath, checks };
  }

  if (fs.existsSync(envPath)) {
    const proceed = await askYesNo({
      message: `${redactHomePath(envPath)} already exists. Overwrite?`,
      defaultValue: false,
    });
    if (isCancelled(proceed) || !proceed) {
      note("skip", "User declined to overwrite existing .env.", {
        id: "env-written",
      });
      return { aborted: true, checks };
    }
  }

  fs.writeFileSync(envPath, contents, { mode: 0o600 });
  fs.chmodSync(envPath, 0o600);

  if (!ensureEnvGitignored(root)) {
    process.stdout.write(
      `  ⚠ .env is not in .gitignore. Add it before committing.\n`,
    );
    note("warn", ".env is not gitignored.", {
      id: "env-gitignored",
    });
  } else {
    note("ok", ".env is gitignored.", { id: "env-gitignored" });
  }

  note("ok", `Wrote ${redactHomePath(envPath)} (mode 0600).`, {
    id: "env-written",
  });

  process.stdout.write(`\n✓ Wrote ${redactHomePath(envPath)} (mode 0600).\n`);
  process.stdout.write(`Next: pnpm mobile:push:sim — should now authenticate.\n`);

  return { wrote: true, envPath, checks };
}

async function main() {
  const { values } = parseCliArgs(process.argv.slice(2));
  if (values.help) {
    process.stdout.write(HELP);
    process.exit(0);
  }

  let outcome;
  try {
    outcome = await runWizard({
      skipValidate: values["skip-validate"],
      noWrite: values["no-write"],
      json: values.json,
    });
  } catch (err) {
    if (values.json) {
      const report = buildReport(TOOL, [
        {
          id: "setup-apns",
          status: "fail",
          summary: "Wizard threw before completion.",
          detail: { message: redactTokenLike(err.message ?? String(err)) },
        },
      ]);
      emitDiagnosticReport(report, { json: true });
    } else {
      process.stderr.write(`\nsetup-apns: ${err.message ?? String(err)}\n`);
    }
    process.exit(1);
  }

  if (values.json) {
    const report = buildReport(TOOL, outcome.checks);
    emitDiagnosticReport(report, { json: true });
  }

  if (outcome.cancelled) {
    process.stdout.write("\nCancelled. No changes written.\n");
    process.exit(0);
  }
  if (outcome.aborted) {
    process.exit(1);
  }
  process.exit(0);
}

const isMain =
  process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isMain) {
  main();
}
