import { strict as assert } from "node:assert";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, it } from "node:test";
import {
  expandHome,
  resolveKeyPath,
  serializeEnv,
  validateBundleId,
  validateKeyId,
  validateP8Path,
  validateTeamId,
} from "./setup-apns.mjs";
import { loadEnvFile } from "./lib/load-env.mjs";

let tmp;
beforeEach(() => {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), "ms-setup-apns-"));
});
afterEach(() => {
  if (tmp && fs.existsSync(tmp)) {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
});

describe("validateKeyId", () => {
  it("accepts a 10-char uppercase alphanumeric id", () => {
    assert.equal(validateKeyId("ABCD1234EF"), null);
    assert.equal(validateKeyId("0123456789"), null);
  });
  it("rejects empty, lowercase, wrong length, or special chars", () => {
    assert.match(validateKeyId(""), /required/);
    assert.match(validateKeyId("abcd1234ef"), /uppercase/);
    assert.match(validateKeyId("ABCDE12345X"), /10/);
    assert.match(validateKeyId("ABCD-1234E"), /uppercase/);
  });
});

describe("validateTeamId", () => {
  it("accepts a 10-char uppercase alphanumeric id", () => {
    assert.equal(validateTeamId("TEAM123XYZ"), null);
  });
  it("rejects empty, lowercase, wrong length", () => {
    assert.match(validateTeamId(""), /required/);
    assert.match(validateTeamId("team123xyz"), /uppercase/);
    assert.match(validateTeamId("TEAM"), /10/);
  });
});

describe("validateBundleId", () => {
  it("accepts a clean reverse-DNS bundle id", () => {
    assert.equal(validateBundleId("com.acme.myapp"), null);
    assert.equal(validateBundleId("com.example.mobilesurfaces"), null);
  });
  it("rejects the .push-type.liveactivity suffix (MS018)", () => {
    assert.match(
      validateBundleId("com.acme.myapp.push-type.liveactivity"),
      /\.push-type\.liveactivity/,
    );
    assert.match(
      validateBundleId("com.acme.myapp.PUSH-TYPE.liveactivity"),
      /\.push-type\.liveactivity/,
    );
  });
  it("rejects single-segment ids", () => {
    assert.match(validateBundleId("com"), /reverse-DNS/);
  });
  it("rejects empty", () => {
    assert.match(validateBundleId(""), /required/);
  });
});

describe("expandHome / resolveKeyPath", () => {
  it("expands ~ to the user's homedir", () => {
    assert.equal(expandHome("~"), os.homedir());
    assert.equal(expandHome("~/foo/bar.p8"), path.join(os.homedir(), "foo/bar.p8"));
  });
  it("leaves absolute paths and bare paths alone", () => {
    assert.equal(expandHome("/abs/foo.p8"), "/abs/foo.p8");
    assert.equal(expandHome("foo.p8"), "foo.p8");
  });
  it("resolveKeyPath produces an absolute path", () => {
    assert.ok(path.isAbsolute(resolveKeyPath("./relative.p8")));
    assert.equal(resolveKeyPath("/abs/foo.p8"), "/abs/foo.p8");
    assert.equal(resolveKeyPath("~/x.p8"), path.join(os.homedir(), "x.p8"));
  });
});

describe("validateP8Path", () => {
  it("rejects a missing file", () => {
    const missing = path.join(tmp, "nope.p8");
    assert.match(validateP8Path(missing), /No file at/);
  });

  it("rejects a file without PEM PRIVATE KEY markers", () => {
    const bogus = path.join(tmp, "fake.p8");
    fs.writeFileSync(bogus, "this is not a key");
    assert.match(validateP8Path(bogus), /doesn't look like a \.p8/);
  });

  it("accepts both standard and EC PRIVATE KEY markers", () => {
    const pkcs8 = path.join(tmp, "pkcs8.p8");
    fs.writeFileSync(
      pkcs8,
      "-----BEGIN PRIVATE KEY-----\nbase64here\n-----END PRIVATE KEY-----\n",
    );
    assert.equal(validateP8Path(pkcs8), null);

    const ec = path.join(tmp, "ec.p8");
    fs.writeFileSync(
      ec,
      "-----BEGIN EC PRIVATE KEY-----\nbase64\n-----END EC PRIVATE KEY-----\n",
    );
    assert.equal(validateP8Path(ec), null);
  });

  it("rejects empty/missing input", () => {
    assert.match(validateP8Path(""), /required/);
  });
});

describe("serializeEnv", () => {
  it("emits keys in the documented order with double-quoted values", () => {
    const out = serializeEnv({
      APNS_BUNDLE_ID: "com.acme.myapp",
      APNS_TEAM_ID: "TEAM123XYZ",
      APNS_KEY_ID: "ABCD1234EF",
      APNS_KEY_PATH: "/Users/glendon/keys/Auth.p8",
      APNS_ENV: "development",
    });
    const lines = out.trim().split("\n");
    // Two leading comment lines, then five key/value lines.
    assert.match(lines[0], /^# Generated by/);
    assert.match(lines[1], /^# Do not commit/);
    assert.deepEqual(lines.slice(2), [
      'APNS_KEY_PATH="/Users/glendon/keys/Auth.p8"',
      'APNS_KEY_ID="ABCD1234EF"',
      'APNS_TEAM_ID="TEAM123XYZ"',
      'APNS_BUNDLE_ID="com.acme.myapp"',
      'APNS_ENV="development"',
    ]);
  });

  it("omits keys that are absent or empty", () => {
    const out = serializeEnv({
      APNS_KEY_ID: "ABCD1234EF",
      APNS_TEAM_ID: "",
    });
    assert.match(out, /APNS_KEY_ID="ABCD1234EF"/);
    assert.equal(/APNS_TEAM_ID=/.test(out), false);
  });

  it("ends with a single trailing newline", () => {
    const out = serializeEnv({ APNS_KEY_ID: "ABCD1234EF" });
    assert.match(out, /\n$/);
    assert.equal(/\n\n$/.test(out), false);
  });
});

describe("loadEnvFile", () => {
  it("loads KEY=VALUE pairs into process.env", () => {
    const envPath = path.join(tmp, ".env");
    fs.writeFileSync(envPath, "TEST_KEY_AAA=hello\nTEST_KEY_BBB=world\n");
    delete process.env.TEST_KEY_AAA;
    delete process.env.TEST_KEY_BBB;
    const result = loadEnvFile(envPath);
    assert.equal(process.env.TEST_KEY_AAA, "hello");
    assert.equal(process.env.TEST_KEY_BBB, "world");
    assert.deepEqual(result.loaded.sort(), ["TEST_KEY_AAA", "TEST_KEY_BBB"]);
    delete process.env.TEST_KEY_AAA;
    delete process.env.TEST_KEY_BBB;
  });

  it("strips a single layer of surrounding quotes", () => {
    const envPath = path.join(tmp, ".env");
    fs.writeFileSync(
      envPath,
      'TEST_KEY_QUOTED="hello world"\nTEST_KEY_SINGLE=\'foo bar\'\n',
    );
    delete process.env.TEST_KEY_QUOTED;
    delete process.env.TEST_KEY_SINGLE;
    loadEnvFile(envPath);
    assert.equal(process.env.TEST_KEY_QUOTED, "hello world");
    assert.equal(process.env.TEST_KEY_SINGLE, "foo bar");
    delete process.env.TEST_KEY_QUOTED;
    delete process.env.TEST_KEY_SINGLE;
  });

  it("does not overwrite keys already set in process.env", () => {
    const envPath = path.join(tmp, ".env");
    fs.writeFileSync(envPath, "TEST_KEY_PRESET=from-file\n");
    process.env.TEST_KEY_PRESET = "from-shell";
    const result = loadEnvFile(envPath);
    assert.equal(process.env.TEST_KEY_PRESET, "from-shell");
    assert.deepEqual(result.skipped, ["TEST_KEY_PRESET"]);
    assert.deepEqual(result.loaded, []);
    delete process.env.TEST_KEY_PRESET;
  });

  it("ignores blank lines and comments", () => {
    const envPath = path.join(tmp, ".env");
    fs.writeFileSync(
      envPath,
      "# leading comment\n\nTEST_KEY_CCC=value\n  # indented comment\n\n",
    );
    delete process.env.TEST_KEY_CCC;
    const result = loadEnvFile(envPath);
    assert.equal(process.env.TEST_KEY_CCC, "value");
    assert.deepEqual(result.loaded, ["TEST_KEY_CCC"]);
    delete process.env.TEST_KEY_CCC;
  });

  it("returns a null filePath when no file exists", () => {
    const result = loadEnvFile(path.join(tmp, "nope.env"));
    assert.equal(result.filePath, null);
    assert.deepEqual(result.loaded, []);
  });

  it("does NOT expand $VAR-style references (predictable behavior)", () => {
    const envPath = path.join(tmp, ".env");
    fs.writeFileSync(envPath, "TEST_KEY_LITERAL=$HOME/foo\n");
    delete process.env.TEST_KEY_LITERAL;
    loadEnvFile(envPath);
    assert.equal(process.env.TEST_KEY_LITERAL, "$HOME/foo");
    delete process.env.TEST_KEY_LITERAL;
  });
});
