// The add-to-existing-Expo flow. Two responsibilities live here because they
// are tightly coupled: (1) planning the exact changes we'd make to the user's
// project, and (2) showing those changes as a recap before any are applied.
// The downstream scaffold consumes the same plan, so what the user confirms
// is exactly what executes.
//
// What Mobile Surfaces requires (packages, plugins, Info.plist keys,
// deployment target, widget files) is read from the template manifest at
// runtime — never duplicated here.

import { cancel, isCancel, note, select, text } from "@clack/prompts";
import path from "node:path";
import pc from "picocolors";
import { cancelled, prompts as copy } from "./copy.mjs";
import { validateTeamId } from "./validators.mjs";

function bail(value) {
  if (isCancel(value)) {
    cancel(cancelled);
    process.exit(0);
  }
  return value;
}

function buildMessage({ message, helper }) {
  if (!helper) return message;
  const railed = helper
    .split("\n")
    .map((line) => pc.gray("│  ") + pc.dim(line))
    .join("\n");
  return `${message}\n${railed}`;
}

export function planChanges({ evidence, manifest }) {
  const plan = {
    packagesToAdd: [...manifest.addPackages],
    appConfigKind: evidence.config?.kind ?? "missing",
    appConfigPath: evidence.config?.path ?? null,
    pluginsToAdd: [],
    infoPlistToAdd: {},
    deploymentTargetTo: null,
    appConfigManual: false,
    widgetTargetDir: manifest.widgetTargetDir,
    widgetFilesToCopy: [...manifest.widgetFiles],
    willPrebuild: true,
    manualFollowups: [],
  };

  if (evidence.config?.kind === "json" && evidence.config.parsed) {
    const expo = evidence.config.parsed;
    const existingPlugins = (expo.plugins ?? []).map((p) =>
      Array.isArray(p) ? p[0] : p,
    );
    plan.pluginsToAdd = manifest.addPlugins.filter(
      (p) => !existingPlugins.includes(p.name),
    );

    const existingInfoPlist = expo.ios?.infoPlist ?? {};
    for (const [k, v] of Object.entries(manifest.addInfoPlist)) {
      if (existingInfoPlist[k] === undefined) {
        plan.infoPlistToAdd[k] = v;
      }
    }

    const cur = parseFloat(expo.ios?.deploymentTarget ?? "0");
    const needed = parseFloat(manifest.deploymentTarget ?? "0");
    if (needed > cur) plan.deploymentTargetTo = manifest.deploymentTarget;
  } else {
    // app.config.js/ts (or no config at all). We can't safely read or write
    // user code in v0.1, so the user gets a paste-ready diff instead.
    plan.appConfigManual = true;
    plan.pluginsToAdd = [...manifest.addPlugins];
    plan.infoPlistToAdd = { ...manifest.addInfoPlist };
    plan.deploymentTargetTo = manifest.deploymentTarget;
    plan.manualFollowups.push(
      evidence.config
        ? `Apply the app.config.${evidence.config.kind} changes shown above by hand.`
        : `Create an app.json or app.config.* with the changes shown above.`,
    );
  }

  if (evidence.hasIosDir) {
    plan.manualFollowups.push(
      "Your existing ios/ folder will be regenerated by prebuild. Custom Xcode changes there will be lost.",
    );
  }

  return plan;
}

function configLabel(config) {
  if (!config) return "(none found)";
  if (config.kind === "json") return "app.json";
  return `app.config.${config.kind}`;
}

function renderFoundRecap(evidence) {
  const config = evidence.config;
  const lines = [
    `Project       ${pc.bold(evidence.packageName)}`,
    `Expo          ${pc.bold(evidence.expoVersion ?? "unknown")}`,
    `Bundle id     ${pc.bold(config?.bundleId ?? "(not set)")}`,
    `Package mgr   ${pc.bold(evidence.packageManager ?? "unknown")}`,
    `Config        ${pc.bold(configLabel(config))}`,
    `ios/ folder   ${evidence.hasIosDir ? pc.bold("present") : pc.dim("not present")}`,
  ];
  if (evidence.pluginsPresent.length > 0) {
    lines.push(`Plugins       ${pc.dim(evidence.pluginsPresent.join(", "))}`);
  }
  note(lines.join("\n"), "What we found");
}

function renderPlanRecap(plan) {
  const sections = [];

  if (plan.packagesToAdd.length > 0) {
    sections.push(
      `Packages\n${plan.packagesToAdd
        .map((p) => "  " + pc.bold(p.name))
        .join("\n")}`,
    );
  }

  const appLines = [];
  for (const p of plan.pluginsToAdd) {
    appLines.push(`  + plugins: ${pc.bold(p.name)}`);
  }
  if (plan.deploymentTargetTo) {
    appLines.push(`  + ios.deploymentTarget: ${pc.bold(plan.deploymentTargetTo)}`);
  }
  for (const [k, v] of Object.entries(plan.infoPlistToAdd)) {
    const valStr = Array.isArray(v) ? `[${v.map(String).join(", ")}]` : String(v);
    appLines.push(`  + ios.infoPlist.${k}: ${pc.bold(valStr)}`);
  }
  if (appLines.length > 0) {
    const header = plan.appConfigManual
      ? `${pc.dim("(diff for " + configLabel({ kind: plan.appConfigKind }) + " — apply by hand)")}\n`
      : "";
    sections.push(`In your app config\n${header}${appLines.join("\n")}`);
  }

  if (plan.widgetFilesToCopy.length > 0) {
    sections.push(
      `New files\n${plan.widgetFilesToCopy
        .map((f) => "  " + pc.bold(path.posix.relative(path.posix.dirname(plan.widgetTargetDir), f)))
        .join("\n")}`,
    );
  }

  if (plan.willPrebuild) {
    sections.push(`Then\n  ${pc.bold("expo prebuild --platform ios")}`);
  }

  note(sections.join("\n\n"), "What I'll add");
}

export async function runExistingExpoPrompts({ evidence, manifest }) {
  renderFoundRecap(evidence);

  const plan = planChanges({ evidence, manifest });

  // Apple Team ID — ask only if we don't already have a real (non-placeholder)
  // value in app.json. JS/TS configs can't be read safely so we always ask.
  const knownTeamId =
    evidence.config?.kind === "json" &&
    evidence.config.parsed?.ios?.appleTeamId &&
    evidence.config.parsed.ios.appleTeamId !== "XXXXXXXXXX"
      ? evidence.config.parsed.ios.appleTeamId
      : null;

  let teamId = knownTeamId;
  if (!knownTeamId) {
    teamId = bail(
      await text({
        message: buildMessage(copy.teamId),
        placeholder: "(skip)",
        validate: validateTeamId,
      }),
    );
    teamId = teamId || null;
  }

  const installNow = bail(
    await select({
      message: buildMessage(copy.installExisting),
      initialValue: true,
      options: [
        { value: true, label: copy.installExisting.yes },
        { value: false, label: copy.installExisting.no },
      ],
    }),
  );

  // Plan recap, then a single confirm before any change is applied.
  renderPlanRecap(plan);

  const proceed = bail(
    await select({
      message: "Apply these changes?",
      initialValue: true,
      options: [
        { value: true, label: "Looks good, apply" },
        { value: false, label: "Cancel" },
      ],
    }),
  );

  if (!proceed) {
    cancel(cancelled);
    process.exit(0);
  }

  return { mode: "existing-expo", evidence, teamId, installNow, plan };
}
