// The add-to-existing-Expo flow. Two responsibilities live here because they
// are tightly coupled: (1) planning the exact changes we'd make to the user's
// project, and (2) showing those changes as a recap before any are applied.
// The downstream scaffold consumes the same plan, so what the user confirms
// is exactly what executes.
//
// What Mobile Surfaces requires (packages, plugins, Info.plist keys,
// deployment target, widget files) is read from the template manifest at
// runtime — never duplicated here.

import path from "node:path";
import pc from "picocolors";
import { cancelled, prompts as copy } from "./copy.mjs";
import { EXIT_CODES } from "./exit-codes.mjs";
import * as defaultUi from "./ui.mjs";
import { validateTeamId } from "./validators.mjs";

// Default selections preserve pre-3A behavior: every surface ships unless
// the caller explicitly opts out. Greenfield reads the selections from the
// surface picker; existing-expo asks the same picker before it calls in.
const DEFAULT_SURFACES = Object.freeze({
  homeWidget: true,
  controlWidget: true,
  lockAccessoryWidget: true,
  standbyWidget: true,
});

// Map a surface id to the widget-target swift file that materializes it.
// Used to filter manifest.widgetFiles down to what'll actually be copied.
const WIDGET_FILE_BY_SURFACE = Object.freeze({
  homeWidget: "MobileSurfacesHomeWidget.swift",
  controlWidget: "MobileSurfacesControlWidget.swift",
  lockAccessoryWidget: "MobileSurfacesLockAccessoryWidget.swift",
  standbyWidget: "MobileSurfacesStandbyWidget.swift",
});

export function planChanges({ evidence, manifest, surfaces = DEFAULT_SURFACES }) {
  const widgetFilesToCopy = manifest.widgetFiles.filter((p) => {
    for (const [id, swiftBasename] of Object.entries(WIDGET_FILE_BY_SURFACE)) {
      if (!surfaces[id] && path.posix.basename(p) === swiftBasename) return false;
    }
    return true;
  });
  const plan = {
    packagesToAdd: [...manifest.addPackages],
    appConfigKind: evidence.config?.kind ?? "missing",
    appConfigPath: evidence.config?.path ?? null,
    pluginsToAdd: [],
    infoPlistToAdd: {},
    entitlementsToAdd: {},
    deploymentTargetTo: null,
    appConfigManual: false,
    widgetTargetDir: manifest.widgetTargetDir,
    widgetFilesToCopy,
    willPrebuild: true,
    manualFollowups: [],
    surfaces: { ...surfaces },
  };

  if (evidence.config?.kind === "json" && evidence.config.parsed) {
    const expo = evidence.config.parsed;
    const existingPlugins = (expo.plugins ?? []).map((p) =>
      Array.isArray(p) ? p[0] : p,
    );
    plan.pluginsToAdd = manifest.addPlugins.filter(
      (p) => !existingPlugins.includes(p.name),
    );

    const existingInfoPlist = expo.ios?.infoPlist ?? {};
    for (const [k, v] of Object.entries(manifest.addInfoPlist)) {
      if (existingInfoPlist[k] === undefined) {
        plan.infoPlistToAdd[k] = v;
      }
    }

    const existingEntitlements = expo.ios?.entitlements ?? {};
    for (const [k, v] of Object.entries(manifest.addEntitlements ?? {})) {
      if (existingEntitlements[k] === undefined) {
        plan.entitlementsToAdd[k] = v;
      }
    }

    const cur = parseFloat(expo.ios?.deploymentTarget ?? "0");
    const needed = parseFloat(manifest.deploymentTarget ?? "0");
    if (needed > cur) plan.deploymentTargetTo = manifest.deploymentTarget;
  } else {
    // app.config.js/ts (or no config at all). We can't safely read or write
    // user code in v0.1, so the user gets a paste-ready diff instead.
    plan.appConfigManual = true;
    plan.pluginsToAdd = [...manifest.addPlugins];
    plan.infoPlistToAdd = { ...manifest.addInfoPlist };
    plan.entitlementsToAdd = { ...(manifest.addEntitlements ?? {}) };
    plan.deploymentTargetTo = manifest.deploymentTarget;
    plan.manualFollowups.push(
      evidence.config
        ? `Apply the app.config.${evidence.config.kind} changes shown above by hand.`
        : `Create an app.json or app.config.* with the changes shown above.`,
    );
  }

  if (evidence.hasIosDir) {
    plan.manualFollowups.push(
      "Your existing ios/ folder will be regenerated by prebuild. Custom Xcode changes there will be lost.",
    );
  }

  return plan;
}

function configLabel(config) {
  if (!config) return "(none found)";
  if (config.kind === "json") return "app.json";
  return `app.config.${config.kind}`;
}

// Rail-prefixed recap. Rendered as a single rail.block so even if the terminal
// is narrow, the column-zero rail prefix is preserved on every row.
function renderFoundRecap(evidence, ui) {
  const config = evidence.config;
  // Order: lead with the things we're about to mutate (config, bundle id),
  // then identifying context (project, package manager). Demote Expo version,
  // ios/ folder, and plugins to the bottom — they're context, not actionable.
  const lines = [
    pc.bold("What we found"),
    "",
    `  config        ${pc.bold(configLabel(config))}`,
    `  bundle id     ${pc.bold(config?.bundleId ?? "(not set)")}`,
    `  project       ${pc.bold(evidence.packageName)}`,
    `  package mgr   ${pc.bold(evidence.packageManager ?? "unknown")}`,
    `  expo          ${pc.dim(evidence.expoVersion ?? "unknown")}`,
    `  ios/ folder   ${evidence.hasIosDir ? pc.dim("present") : pc.dim("not present")}`,
  ];
  if (evidence.pluginsPresent.length > 0) {
    lines.push(`  plugins       ${pc.dim(evidence.pluginsPresent.join(", "))}`);
  }
  lines.push("");
  ui.rail.block(lines.join("\n"));
}

function renderPlanRecap(plan, ui) {
  const lines = [pc.bold("Changes to apply"), ""];

  // Echo the surface selections so the user sees their choices reflected
  // before "Apply these changes?". Live activity + dynamic island always
  // ship; only home + control widgets are toggleable.
  lines.push("  " + pc.bold("surfaces"));
  lines.push(`    live activity + dynamic island  ${pc.dim("(always)")}`);
  lines.push(`    home widget                     ${plan.surfaces.homeWidget ? pc.bold("yes") : pc.dim("no")}`);
  lines.push(`    control widget                  ${plan.surfaces.controlWidget ? pc.bold("yes") : pc.dim("no")}`);
  lines.push("");

  if (plan.packagesToAdd.length > 0) {
    lines.push("  " + pc.bold("packages"));
    for (const p of plan.packagesToAdd) {
      lines.push("    " + p.name);
    }
    lines.push("");
  }

  const appLines = [];
  for (const p of plan.pluginsToAdd) {
    appLines.push(`+ plugins: ${pc.bold(p.name)}`);
  }
  if (plan.deploymentTargetTo) {
    appLines.push(`+ ios.deploymentTarget: ${pc.bold(plan.deploymentTargetTo)}`);
  }
  for (const [k, v] of Object.entries(plan.infoPlistToAdd)) {
    const valStr = Array.isArray(v) ? `[${v.map(String).join(", ")}]` : String(v);
    appLines.push(`+ ios.infoPlist.${k}: ${pc.bold(valStr)}`);
  }
  for (const [k, v] of Object.entries(plan.entitlementsToAdd)) {
    const valStr = Array.isArray(v) ? `[${v.map(String).join(", ")}]` : String(v);
    appLines.push(`+ ios.entitlements.${k}: ${pc.bold(valStr)}`);
  }
  if (appLines.length > 0) {
    const heading = plan.appConfigManual
      ? `app config ${pc.dim(`(apply by hand to ${configLabel({ kind: plan.appConfigKind })})`)}`
      : "app config";
    lines.push("  " + pc.bold(heading));
    for (const l of appLines) lines.push("    " + l);
    lines.push("");
  }

  if (plan.widgetFilesToCopy.length > 0) {
    const widgetParent = path.posix.dirname(plan.widgetTargetDir);
    lines.push("  " + pc.bold("new files"));
    for (const f of plan.widgetFilesToCopy) {
      lines.push("    " + path.posix.relative(widgetParent, f));
    }
    lines.push("");
  }

  if (plan.willPrebuild) {
    lines.push("  " + pc.bold("then"));
    lines.push("    expo prebuild --platform ios");
    lines.push("");
  }

  ui.rail.block(lines.join("\n"));
}

export async function runExistingExpoPrompts({ evidence, manifest, overrides = {}, yes = false, ui = defaultUi }) {
  ui.rail.step(2, 5, "Detection");
  renderFoundRecap(evidence, ui);

  ui.rail.step(3, 5, "Surfaces");

  // Same picker as greenfield. Live Activity + Dynamic Island always ship.
  const homeWidget = overrides.homeWidget !== undefined
    ? overrides.homeWidget
    : yes
      ? true
      : await ui.askConfirm({
          message: copy.surfaces.homeWidget.message,
          defaultValue: true,
        });

  const controlWidget = overrides.controlWidget !== undefined
    ? overrides.controlWidget
    : yes
      ? true
      : await ui.askConfirm({
          message: copy.surfaces.controlWidget.message,
          defaultValue: true,
        });

  const plan = planChanges({
    evidence,
    manifest,
    surfaces: { homeWidget, controlWidget },
  });

  ui.rail.step(4, 5, "Plan");

  // Apple Team ID — ask only if we don't already have a real (non-placeholder)
  // value in app.json. JS/TS configs can't be read safely so we always ask.
  const knownTeamId =
    evidence.config?.kind === "json" &&
    evidence.config.parsed?.ios?.appleTeamId &&
    evidence.config.parsed.ios.appleTeamId !== "XXXXXXXXXX"
      ? evidence.config.parsed.ios.appleTeamId
      : null;

  let teamId;
  if (overrides.teamId !== undefined) {
    teamId = overrides.teamId || null;
  } else if (knownTeamId) {
    teamId = knownTeamId;
  } else if (yes) {
    teamId = null;
  } else {
    const answer = await ui.askText({
      message: copy.teamId.message,
      defaultValue: "",
      validate: validateTeamId,
    });
    teamId = answer || null;
  }

  const installNow = overrides.installNow !== undefined
    ? overrides.installNow
    : yes
      ? true
      : await ui.askSelect({
          message: copy.installExisting.message,
          defaultValue: true,
          options: [
            { value: true, label: copy.installExisting.yes, hint: copy.installExisting.yesHint },
            { value: false, label: copy.installExisting.no },
          ],
        });

  // Plan recap, then a single confirm before any change is applied. --yes
  // skips both the recap header confirmation and the "are you sure" prompt.
  renderPlanRecap(plan, ui);

  if (!yes) {
    const proceed = await ui.askConfirm({
      message: copy.confirmExisting.message,
      defaultValue: true,
    });

    if (!proceed) {
      ui.log.message(pc.dim(cancelled));
      process.exit(EXIT_CODES.SUCCESS);
    }
  }

  return { mode: "existing-expo", evidence, teamId, installNow, plan };
}
