// The add-to-existing-Expo flow. Two responsibilities live here because they
// are tightly coupled: (1) planning the exact changes we'd make to the user's
// project, and (2) showing those changes as a recap before any are applied.
// The downstream scaffold consumes the same plan, so what the user confirms
// is exactly what executes.
//
// What Mobile Surfaces requires (packages, plugins, Info.plist keys,
// deployment target, widget files) is read from the template manifest at
// runtime — never duplicated here.

import path from "node:path";
import pc from "picocolors";
import { cancelled, prompts as copy } from "./copy.mjs";
import { askConfirm, askSelect, askText, log, rail } from "./ui.mjs";
import { validateTeamId } from "./validators.mjs";

export function planChanges({ evidence, manifest }) {
  const plan = {
    packagesToAdd: [...manifest.addPackages],
    appConfigKind: evidence.config?.kind ?? "missing",
    appConfigPath: evidence.config?.path ?? null,
    pluginsToAdd: [],
    infoPlistToAdd: {},
    deploymentTargetTo: null,
    appConfigManual: false,
    widgetTargetDir: manifest.widgetTargetDir,
    widgetFilesToCopy: [...manifest.widgetFiles],
    willPrebuild: true,
    manualFollowups: [],
  };

  if (evidence.config?.kind === "json" && evidence.config.parsed) {
    const expo = evidence.config.parsed;
    const existingPlugins = (expo.plugins ?? []).map((p) =>
      Array.isArray(p) ? p[0] : p,
    );
    plan.pluginsToAdd = manifest.addPlugins.filter(
      (p) => !existingPlugins.includes(p.name),
    );

    const existingInfoPlist = expo.ios?.infoPlist ?? {};
    for (const [k, v] of Object.entries(manifest.addInfoPlist)) {
      if (existingInfoPlist[k] === undefined) {
        plan.infoPlistToAdd[k] = v;
      }
    }

    const cur = parseFloat(expo.ios?.deploymentTarget ?? "0");
    const needed = parseFloat(manifest.deploymentTarget ?? "0");
    if (needed > cur) plan.deploymentTargetTo = manifest.deploymentTarget;
  } else {
    // app.config.js/ts (or no config at all). We can't safely read or write
    // user code in v0.1, so the user gets a paste-ready diff instead.
    plan.appConfigManual = true;
    plan.pluginsToAdd = [...manifest.addPlugins];
    plan.infoPlistToAdd = { ...manifest.addInfoPlist };
    plan.deploymentTargetTo = manifest.deploymentTarget;
    plan.manualFollowups.push(
      evidence.config
        ? `Apply the app.config.${evidence.config.kind} changes shown above by hand.`
        : `Create an app.json or app.config.* with the changes shown above.`,
    );
  }

  if (evidence.hasIosDir) {
    plan.manualFollowups.push(
      "Your existing ios/ folder will be regenerated by prebuild. Custom Xcode changes there will be lost.",
    );
  }

  return plan;
}

function configLabel(config) {
  if (!config) return "(none found)";
  if (config.kind === "json") return "app.json";
  return `app.config.${config.kind}`;
}

// Rail-prefixed recap. Rendered as a single rail.block so even if the terminal
// is narrow, the column-zero rail prefix is preserved on every row.
function renderFoundRecap(evidence) {
  const config = evidence.config;
  const lines = [
    pc.bold("What we found"),
    "",
    `  Project       ${pc.bold(evidence.packageName)}`,
    `  Expo          ${pc.bold(evidence.expoVersion ?? "unknown")}`,
    `  Bundle id     ${pc.bold(config?.bundleId ?? "(not set)")}`,
    `  Package mgr   ${pc.bold(evidence.packageManager ?? "unknown")}`,
    `  Config        ${pc.bold(configLabel(config))}`,
    `  ios/ folder   ${evidence.hasIosDir ? pc.bold("present") : pc.dim("not present")}`,
  ];
  if (evidence.pluginsPresent.length > 0) {
    lines.push(`  Plugins       ${pc.dim(evidence.pluginsPresent.join(", "))}`);
  }
  lines.push("");
  rail.block(lines.join("\n"));
}

function renderPlanRecap(plan) {
  const lines = [pc.bold("What I'll add"), ""];

  if (plan.packagesToAdd.length > 0) {
    lines.push("  " + pc.bold("Packages"));
    for (const p of plan.packagesToAdd) {
      lines.push("    " + p.name);
    }
    lines.push("");
  }

  const appLines = [];
  for (const p of plan.pluginsToAdd) {
    appLines.push(`+ plugins: ${pc.bold(p.name)}`);
  }
  if (plan.deploymentTargetTo) {
    appLines.push(`+ ios.deploymentTarget: ${pc.bold(plan.deploymentTargetTo)}`);
  }
  for (const [k, v] of Object.entries(plan.infoPlistToAdd)) {
    const valStr = Array.isArray(v) ? `[${v.map(String).join(", ")}]` : String(v);
    appLines.push(`+ ios.infoPlist.${k}: ${pc.bold(valStr)}`);
  }
  if (appLines.length > 0) {
    const heading = plan.appConfigManual
      ? `In your app config ${pc.dim(`(apply by hand to ${configLabel({ kind: plan.appConfigKind })})`)}`
      : "In your app config";
    lines.push("  " + pc.bold(heading));
    for (const l of appLines) lines.push("    " + l);
    lines.push("");
  }

  if (plan.widgetFilesToCopy.length > 0) {
    const widgetParent = path.posix.dirname(plan.widgetTargetDir);
    lines.push("  " + pc.bold("New files"));
    for (const f of plan.widgetFilesToCopy) {
      lines.push("    " + path.posix.relative(widgetParent, f));
    }
    lines.push("");
  }

  if (plan.willPrebuild) {
    lines.push("  " + pc.bold("Then"));
    lines.push("    expo prebuild --platform ios");
    lines.push("");
  }

  rail.block(lines.join("\n"));
}

export async function runExistingExpoPrompts({ evidence, manifest }) {
  rail.step(2, 4, "Detection");
  renderFoundRecap(evidence);

  const plan = planChanges({ evidence, manifest });

  rail.step(3, 4, "Plan");

  // Apple Team ID — ask only if we don't already have a real (non-placeholder)
  // value in app.json. JS/TS configs can't be read safely so we always ask.
  const knownTeamId =
    evidence.config?.kind === "json" &&
    evidence.config.parsed?.ios?.appleTeamId &&
    evidence.config.parsed.ios.appleTeamId !== "XXXXXXXXXX"
      ? evidence.config.parsed.ios.appleTeamId
      : null;

  let teamId = knownTeamId;
  if (!knownTeamId) {
    teamId = await askText({
      message: copy.teamId.message,
      defaultValue: "",
      validate: validateTeamId,
    });
    teamId = teamId || null;
  }

  const installNow = await askSelect({
    message: copy.installExisting.message,
    defaultValue: true,
    options: [
      { value: true, label: copy.installExisting.yes, hint: copy.installExisting.yesHint },
      { value: false, label: copy.installExisting.no },
    ],
  });

  // Plan recap, then a single confirm before any change is applied.
  renderPlanRecap(plan);

  const proceed = await askConfirm({
    message: "Apply these changes?",
    defaultValue: true,
  });

  if (!proceed) {
    log.message(pc.dim(cancelled));
    process.exit(0);
  }

  return { mode: "existing-expo", evidence, teamId, installNow, plan };
}
