import type { LiveSurfaceSnapshot } from "./index";

// Generated from data/surface-fixtures by scripts/generate-surface-fixtures.mjs.
// Edit the JSON fixtures, then run pnpm surface:check.
export const surfaceFixtureSnapshots = {
  "queued": {
    "id": "fixture-queued",
    "surfaceId": "surface-queued",
    "state": "queued",
    "modeLabel": "queued",
    "contextLabel": "starter",
    "statusLine": "queued · ready to start",
    "primaryText": "Surface queued",
    "secondaryText": "Use this as the initial state before a Live Activity starts changing.",
    "actionLabel": "Open surface",
    "estimatedSeconds": 900,
    "morePartsCount": 0,
    "progress": 0,
    "stage": "prompted",
    "deepLink": "mobilesurfaces://surface/surface-queued"
  },
  "attention": {
    "id": "fixture-attention",
    "surfaceId": "surface-attention",
    "state": "attention",
    "modeLabel": "attention",
    "contextLabel": "urgent",
    "statusLine": "attention · user-visible update",
    "primaryText": "Attention needed",
    "secondaryText": "Use this state for alert-worthy pushes or prominent ActivityKit updates.",
    "actionLabel": "Review",
    "estimatedSeconds": 120,
    "morePartsCount": 1,
    "progress": 0.15,
    "stage": "prompted",
    "deepLink": "mobilesurfaces://surface/surface-attention"
  },
  "activeProgress": {
    "id": "fixture-active-progress",
    "surfaceId": "surface-active-progress",
    "state": "active",
    "modeLabel": "active",
    "contextLabel": "progress",
    "statusLine": "active · 50%",
    "primaryText": "Surface in progress",
    "secondaryText": "The same snapshot feeds the app view and ActivityKit content state.",
    "actionLabel": "View progress",
    "estimatedSeconds": 360,
    "morePartsCount": 0,
    "progress": 0.5,
    "stage": "inProgress",
    "deepLink": "mobilesurfaces://surface/surface-active-progress"
  },
  "activeCountdown": {
    "id": "fixture-active-countdown",
    "surfaceId": "surface-active-countdown",
    "state": "active",
    "modeLabel": "countdown",
    "contextLabel": "timer",
    "statusLine": "active · 30s remaining",
    "primaryText": "Countdown in progress",
    "secondaryText": "Preview time-sensitive progress changes without connecting a backend.",
    "actionLabel": "Continue",
    "estimatedSeconds": 30,
    "morePartsCount": 0,
    "progress": 0.35,
    "stage": "inProgress",
    "deepLink": "mobilesurfaces://surface/surface-active-countdown"
  },
  "paused": {
    "id": "fixture-paused",
    "surfaceId": "surface-paused",
    "state": "paused",
    "modeLabel": "paused",
    "contextLabel": "waiting",
    "statusLine": "paused · no update needed",
    "primaryText": "Surface paused",
    "secondaryText": "A paused surface can stay visible without noisy updates.",
    "actionLabel": "Open surface",
    "estimatedSeconds": 1800,
    "morePartsCount": 0,
    "progress": 0.4,
    "stage": "prompted",
    "deepLink": "mobilesurfaces://surface/surface-paused"
  },
  "badTiming": {
    "id": "fixture-bad-timing",
    "surfaceId": "surface-none-bad-timing",
    "state": "bad_timing",
    "modeLabel": "bad timing",
    "contextLabel": "suppressed",
    "statusLine": "suppressed · not now",
    "primaryText": "Surface suppressed",
    "secondaryText": "Use this state when the app decides not to interrupt the user.",
    "actionLabel": "Snooze",
    "estimatedSeconds": 0,
    "morePartsCount": 0,
    "progress": 0,
    "stage": "completing",
    "deepLink": "mobilesurfaces://today"
  },
  "completed": {
    "id": "fixture-completed",
    "surfaceId": "surface-completed",
    "state": "completed",
    "modeLabel": "completed",
    "contextLabel": "finished",
    "statusLine": "completed · ready to end",
    "primaryText": "Surface completed",
    "secondaryText": "End the activity locally or with an ActivityKit push.",
    "actionLabel": "Done",
    "estimatedSeconds": 0,
    "morePartsCount": 0,
    "progress": 1,
    "stage": "completing",
    "deepLink": "mobilesurfaces://surface/surface-completed"
  },
  "activeDetails": {
    "id": "fixture-active-details",
    "surfaceId": "surface-active-details",
    "state": "active",
    "modeLabel": "details",
    "contextLabel": "expanded",
    "statusLine": "active · more detail available",
    "primaryText": "Surface has more detail",
    "secondaryText": "Use morePartsCount when a surface has additional detail in the app.",
    "actionLabel": "View details",
    "estimatedSeconds": 420,
    "morePartsCount": 2,
    "progress": 0.75,
    "stage": "inProgress",
    "deepLink": "mobilesurfaces://surface/surface-active-details"
  }
} as const satisfies Record<string, LiveSurfaceSnapshot>;
