import type { TrapEntry } from "./traps.ts";

// Generated from data/traps.json by scripts/generate-traps-data.mjs. The
// catalog is the source of truth; do not edit this file by hand. Run
// pnpm surface:check (which calls --check) to verify drift; run
// node --experimental-strip-types scripts/generate-traps-data.mjs to
// regenerate after editing data/traps.json.

export const traps: readonly TrapEntry[] = [
  {
    "id": "MS001",
    "title": "Live Activity adapter boundary",
    "severity": "error",
    "detection": "static",
    "tags": [
      "live-activity",
      "contract"
    ],
    "summary": "Application code under apps/*/src/ must import the live-activity adapter through the boundary re-export, never directly from @mobile-surfaces/live-activity.",
    "symptom": "Compile-time imports look fine, but the project loses the swap point for switching to expo-live-activity, expo-widgets, or a custom native module without touching call sites.",
    "fix": "Import from apps/mobile/src/liveActivity (the boundary re-export) instead of @mobile-surfaces/live-activity directly. Add new methods to the adapter contract first, not at the call site.",
    "enforcement": {
      "script": "scripts/check-adapter-boundary.mjs"
    },
    "docs": [
      "docs/architecture.md#adapter-contract"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS002",
    "title": "ActivityKit attribute file byte-identity",
    "severity": "error",
    "detection": "static",
    "tags": [
      "live-activity",
      "swift"
    ],
    "summary": "MobileSurfacesActivityAttributes.swift in packages/live-activity/ios/ and apps/mobile/targets/widget/ must be byte-identical.",
    "symptom": "Activity starts on the device but never appears on the Lock Screen. No log, no error. ActivityKit silently drops updates whose decoded ContentState shape does not match the widget extension's struct.",
    "fix": "Edit one file and copy verbatim into the other; pnpm surface:check verifies byte-identity. Phase 5 will replace this duplication with a local Swift Package once @bacons/apple-targets and React Native lift the upstream blocks.",
    "enforcement": {
      "script": "scripts/check-activity-attributes.mjs"
    },
    "docs": [
      "docs/architecture.md#native-constraints"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS003",
    "title": "Swift ContentState fields and JSON keys match Zod liveSurfaceActivityContentState",
    "severity": "error",
    "detection": "static",
    "tags": [
      "live-activity",
      "swift",
      "contract"
    ],
    "summary": "MobileSurfacesActivityAttributes.ContentState must declare the same fields, types, and JSON keys as liveSurfaceActivityContentState in packages/surface-contracts/src/schema.ts. Both Swift attribute files participate; the JSON-key shape is what ActivityKit decodes from the push payload.",
    "symptom": "Push lands at APNs (200) but the Lock Screen view stays on its old state. The Codable decoder silently fails on a renamed key or a type mismatch and ActivityKit drops the update without surfacing an error.",
    "fix": "Update the Zod source first, regenerate the JSON Schema (pnpm surface:check), then mirror the field change into both Swift attribute files. Project payloads through toLiveActivityContentState rather than hand-rolling JSON so the JS layer cannot diverge from the contract.",
    "enforcement": {
      "script": "scripts/check-activity-attributes.mjs"
    },
    "since": "1.0.0"
  },
  {
    "id": "MS004",
    "title": "Swift Stage enum cases match Zod liveSurfaceStage",
    "severity": "error",
    "detection": "static",
    "tags": [
      "live-activity",
      "swift",
      "contract"
    ],
    "summary": "The Stage enum in MobileSurfacesActivityAttributes.swift must cover exactly the cases listed in liveSurfaceStage.",
    "symptom": "ContentState decodes but the stage value falls back to a default. Your Lock Screen never shows 'completing' even after the job is done.",
    "fix": "Add or remove cases in lockstep: Zod first, regenerate the schema, mirror into both Swift files.",
    "enforcement": {
      "script": "scripts/check-activity-attributes.mjs"
    },
    "since": "1.0.0"
  },
  {
    "id": "MS006",
    "title": "Generated JSON Schema must match Zod source",
    "severity": "error",
    "detection": "static",
    "tags": [
      "contract",
      "push"
    ],
    "summary": "packages/surface-contracts/schema.json must be regenerated whenever the Zod source changes; CI fails if the committed file is stale.",
    "symptom": "Backends validating with Ajv or jsonschema accept payloads the runtime then rejects (or vice versa). Consumers pinning the unpkg URL get out-of-date validation.",
    "fix": "Run node --experimental-strip-types scripts/build-schema.mjs and commit the result.",
    "enforcement": {
      "script": "scripts/build-schema.mjs"
    },
    "since": "1.0.0"
  },
  {
    "id": "MS007",
    "title": "All committed fixtures must parse as LiveSurfaceSnapshot",
    "severity": "error",
    "detection": "static",
    "tags": [
      "contract"
    ],
    "summary": "Every JSON file under data/surface-fixtures/ must parse via the v1 discriminated union (after $schema is stripped).",
    "symptom": "Tests that exercise fixtures pass locally but fail in CI on a fixture nobody noticed was malformed; or fixture-driven previews silently render placeholder data.",
    "fix": "Run pnpm surface:check and address any reported issues. Update data/surface-fixtures/index.json if the fixture was newly added.",
    "enforcement": {
      "script": "scripts/validate-surface-fixtures.mjs"
    },
    "since": "1.0.0"
  },
  {
    "id": "MS008",
    "title": "Snapshot kind must match its projection slice",
    "severity": "error",
    "detection": "static",
    "tags": [
      "contract"
    ],
    "summary": "kind: 'widget' requires a widget slice; kind: 'control' requires a control slice; kind: 'notification' requires a notification slice.",
    "symptom": "safeParse throws a discriminated-union error at the wire boundary; or worse, an old code path bypasses safeParse and a missing slice causes downstream surfaces to render placeholder data.",
    "fix": "Pair every kind change with its slice. Use the projection helper for the kind (toWidgetTimelineEntry, toControlValueProvider, toNotificationContentPayload) rather than reaching into the snapshot directly.",
    "enforcement": {
      "script": "scripts/surface-contracts.test.mjs"
    },
    "since": "1.0.0"
  },
  {
    "id": "MS009",
    "title": "Generated TypeScript fixtures must match JSON sources",
    "severity": "error",
    "detection": "static",
    "tags": [
      "contract"
    ],
    "summary": "packages/surface-contracts/src/fixtures.ts is generated from data/surface-fixtures/*.json and must not drift.",
    "symptom": "Test imports reference the TS fixtures but get a stale shape; the harness shows different state than the fixture file on disk.",
    "fix": "Run node scripts/generate-surface-fixtures.mjs and commit. CI runs the same with --check.",
    "enforcement": {
      "script": "scripts/generate-surface-fixtures.mjs"
    },
    "since": "1.0.0"
  },
  {
    "id": "MS010",
    "title": "Toolchain preflight (Node 24, pnpm, Xcode 26+)",
    "severity": "warning",
    "detection": "config",
    "tags": [
      "toolchain"
    ],
    "summary": "pnpm dev:doctor verifies Node 24, pnpm 10, Xcode major 26+, and simulator availability before iOS work begins.",
    "symptom": "Builds fail with confusing Swift compiler errors, simulator launches that hang, or pnpm refusing to install. None of which point at the actual cause (a stale toolchain row).",
    "fix": "Run pnpm dev:doctor. Update Xcode and re-run if the major version is below 26. Use Node 24.",
    "enforcement": {
      "script": "scripts/doctor.mjs"
    },
    "since": "1.0.0"
  },
  {
    "id": "MS011",
    "title": "ActivityKit payload size ceiling (4 KB / 5 KB broadcast)",
    "severity": "error",
    "detection": "runtime",
    "tags": [
      "live-activity",
      "push"
    ],
    "summary": "Per-activity Live Activity pushes are bounded at 4 KB; iOS 18 broadcast pushes at 5 KB.",
    "symptom": "APNs returns 413 PayloadTooLarge, or accepts the payload but iOS silently drops the update. Long localized strings or accumulated morePartsCount details are common offenders.",
    "fix": "Trim the snapshot. Shorten secondaryText, lower morePartsCount, or split a state into two smaller pushes. Validate by sending the projection through toLiveActivityContentState and measuring.",
    "iosMin": "16.2",
    "appleDocs": [
      "https://developer.apple.com/documentation/usernotifications/sending-notification-requests-to-apns"
    ],
    "docs": [
      "docs/push.md#error-responses"
    ],
    "since": "1.0.0",
    "errorClasses": [
      "PayloadTooLargeError"
    ]
  },
  {
    "id": "MS012",
    "title": "iOS deployment target must be 17.2 or higher",
    "severity": "error",
    "detection": "config",
    "tags": [
      "ios-version",
      "config"
    ],
    "summary": "Mobile Surfaces commits to push-to-start tokens (Activity<…>.pushToStartTokenUpdates) without if #available ceremony; deployment target below 17.2 breaks the live-activity adapter at compile time.",
    "symptom": "Swift compile errors on pushToStartTokenUpdates references, or a build that succeeds on a lower target only because the symbol was guarded, and then push-to-start silently never works on iOS 16 devices.",
    "fix": "Set ios.deploymentTarget to '17.2' in apps/mobile/app.json (or via expo-build-properties) and rerun prebuild.",
    "iosMin": "17.2",
    "docs": [
      "docs/compatibility.md"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS013",
    "title": "App Group entitlement must match host app and widget extension",
    "severity": "error",
    "detection": "static",
    "tags": [
      "app-group",
      "widget",
      "control",
      "config"
    ],
    "summary": "apps/mobile/app.json, apps/mobile/targets/widget/generated.entitlements, MobileSurfacesSharedState.swift, and the host-side TS constants in apps/mobile/src must all declare the same com.apple.security.application-groups identifier.",
    "symptom": "Widget renders placeholder forever; control widget never reads the toggle state. No error: the entitlement mismatch makes both sides read separate App Group containers.",
    "fix": "Set the same group identifier on every side (default 'group.com.example.mobilesurfaces'; rename via pnpm surface:rename) and rerun prebuild. check-app-group-identity verifies parity across all five declaration sites.",
    "enforcement": {
      "script": "scripts/check-app-group-identity.mjs"
    },
    "docs": [
      "docs/ios-environment.md"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS014",
    "title": "APNs token environment must match the build environment",
    "severity": "error",
    "detection": "runtime",
    "tags": [
      "push",
      "tokens"
    ],
    "summary": "Tokens minted by a development build cannot authenticate against the production APNs endpoint, and vice versa.",
    "symptom": "APNs responds 400 BadDeviceToken. The token is valid; it just belongs to the other environment.",
    "fix": "Use environment: 'development' for dev-client and expo run:ios builds, environment: 'production' only for TestFlight and App Store builds. Track which environment minted each token.",
    "docs": [
      "docs/push.md#error-responses"
    ],
    "since": "1.0.0",
    "errorClasses": [
      "BadDeviceTokenError"
    ]
  },
  {
    "id": "MS015",
    "title": "Push priority 5 vs 10 budget rules",
    "severity": "warning",
    "detection": "runtime",
    "tags": [
      "push",
      "live-activity"
    ],
    "summary": "Live Activity priority 10 is for immediate user-visible updates and is heavily budgeted by iOS; sustained priority 10 sends are silently throttled.",
    "symptom": "Updates land for the first few pushes then mysteriously stop arriving on the device. APNs returns 200; iOS still drops them. Logs show TooManyRequests bursts.",
    "fix": "Default to priority 5 for Live Activity content-state updates. Reserve priority 10 for state transitions the user must see immediately (queued→active, completed).",
    "docs": [
      "docs/push.md#error-responses"
    ],
    "since": "1.0.0",
    "errorClasses": [
      "TooManyRequestsError"
    ]
  },
  {
    "id": "MS016",
    "title": "Subscribe to onPushToStartToken at mount, not on demand",
    "severity": "error",
    "detection": "static",
    "tags": [
      "tokens",
      "live-activity"
    ],
    "summary": "iOS only delivers push-to-start tokens through Activity<…>.pushToStartTokenUpdates as an async sequence; getPushToStartToken() always resolves null.",
    "symptom": "Backend never receives a push-to-start token, or only receives one after a manual app re-launch. Remote Live Activity start never fires for users who have not opened the app since install.",
    "fix": "Subscribe via liveActivityAdapter.addListener('onPushToStartToken', …) inside a mount-time effect. Re-store the token on every emission, since Apple may rotate at cold launch or system rotation.",
    "iosMin": "17.2",
    "docs": [
      "docs/push.md#token-taxonomy"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS017",
    "title": "apps/mobile/ios/ is generated; do not edit",
    "severity": "error",
    "detection": "static",
    "tags": [
      "cng",
      "config"
    ],
    "summary": "Continuous Native Generation rebuilds apps/mobile/ios/ from app.json, packages/live-activity/, and apps/mobile/targets/widget/. Manual edits are wiped on the next prebuild.",
    "symptom": "An Xcode change you made to fix a build issue disappears after pnpm mobile:prebuild:ios and the original problem returns. Or the change persists locally but breaks every other contributor.",
    "fix": "Edit the source files instead: app.json for plist/entitlements, packages/live-activity/ios/ for native module Swift, apps/mobile/targets/widget/ for the WidgetKit target. Then rerun prebuild.",
    "docs": [
      "docs/ios-environment.md"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS018",
    "title": "APNS_BUNDLE_ID must not include the .push-type.liveactivity suffix",
    "severity": "error",
    "detection": "runtime",
    "tags": [
      "push",
      "config"
    ],
    "summary": "The push SDK auto-appends .push-type.liveactivity to the apns-topic; passing it pre-suffixed produces a malformed topic header.",
    "symptom": "APNs responds 400 TopicDisallowed even though your auth key is correctly enabled for the app. The topic header has the suffix doubled or in the wrong position.",
    "fix": "Set APNS_BUNDLE_ID to the bare bundle id (e.g. com.example.mobilesurfaces). The SDK and scripts/send-apns.mjs both handle the suffix internally.",
    "docs": [
      "docs/push.md#error-responses"
    ],
    "since": "1.0.0",
    "errorClasses": [
      "TopicDisallowedError"
    ]
  },
  {
    "id": "MS019",
    "title": "FB21158660: push-to-start tokens silent after force-quit",
    "severity": "info",
    "detection": "advisory",
    "tags": [
      "tokens",
      "live-activity"
    ],
    "summary": "Apple-reported bug. After the user force-quits the app, pushToStartTokenUpdates may stop emitting until the next OS push wakes the app, but the previously-issued token still authenticates against APNs (200 response, no actual activity start).",
    "symptom": "Backend successfully sends a remote start, gets 200, but the Lock Screen never shows the activity. User has force-quit the app since the last token rotation.",
    "fix": "No client workaround. Document in customer-support runbooks: 'If the Lock Screen activity does not appear after a remote-start push, ask the user to open the app once.'",
    "iosMin": "17.2",
    "docs": [
      "docs/push.md#fb21158660-push-to-start-after-force-quit"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS020",
    "title": "Per-activity and push-to-start tokens may rotate at any time",
    "severity": "error",
    "detection": "static",
    "tags": [
      "tokens"
    ],
    "summary": "Both pushTokenUpdates and pushToStartTokenUpdates may emit fresh values at any moment (cold launch, system rotation, foreground transition).",
    "symptom": "Backend send to a stored token returns 410 Unregistered or 400 BadDeviceToken on a previously-working device. The user did nothing wrong; the OS rotated the token.",
    "fix": "Treat the latest event as authoritative. Re-store on every emission keyed by user/device id, and update the active record rather than appending.",
    "docs": [
      "docs/push.md#token-taxonomy"
    ],
    "since": "1.0.0",
    "errorClasses": [
      "UnregisteredError"
    ]
  },
  {
    "id": "MS021",
    "title": "Discard per-activity tokens when the activity ends",
    "severity": "warning",
    "detection": "runtime",
    "tags": [
      "tokens",
      "live-activity"
    ],
    "summary": "Once onActivityStateChange reports 'ended' or 'dismissed', the per-activity push token is dead; sending to it is accepted by APNs (200) but iOS will not surface anything.",
    "symptom": "Backend keeps spending sends on a token that produces no user-visible effect. No error, just silent drops.",
    "fix": "Wire onActivityStateChange to your token store; mark tokens for the activity as terminal and stop selecting them for sends.",
    "docs": [
      "docs/push.md#token-taxonomy"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS023",
    "title": "Per-activity tokens are bound to a single Activity instance",
    "severity": "warning",
    "detection": "runtime",
    "tags": [
      "tokens"
    ],
    "summary": "A new Activity.request mints a fresh per-activity token; tokens from a previous run cannot drive the new activity.",
    "symptom": "Update lands at APNs (200) but appears not to do anything. Reading the harness shows a different per-activity token than what your backend stored.",
    "fix": "Re-store on every onPushToken emission; treat tokens as activity-scoped, not user-scoped.",
    "docs": [
      "docs/push.md#token-taxonomy"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS024",
    "title": "Project must depend on @mobile-surfaces/surface-contracts (and push, when sending)",
    "severity": "error",
    "detection": "config",
    "tags": [
      "contract",
      "push"
    ],
    "summary": "Foreign Expo projects auditing as Mobile Surfaces consumers must list the contract package; backends sending pushes must additionally list @mobile-surfaces/push.",
    "symptom": "Type errors on snapshot helpers, or hand-rolled APNs code that diverges from the validated contract. The failure mode is wire-level drift between client and server.",
    "fix": "Add @mobile-surfaces/surface-contracts on every layer that emits or consumes a snapshot. Add @mobile-surfaces/push on the backend. Both packages release together (linked group).",
    "docs": [
      "docs/backend-integration.md"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS025",
    "title": "App Group declared in app.json",
    "severity": "error",
    "detection": "config",
    "tags": [
      "app-group",
      "config"
    ],
    "summary": "app.json must declare a com.apple.security.application-groups entry for widgets and controls to share state with the host app.",
    "symptom": "Widget extension reads its placeholder snapshot, never the live one. Control toggle does nothing visible. No log message; the App Group is just absent.",
    "fix": "Add the entitlement to apps/mobile/app.json under expo.ios.entitlements. Match it on the widget target's expo-target.config.js.",
    "docs": [
      "docs/ios-environment.md"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS026",
    "title": "Widget target managed by @bacons/apple-targets",
    "severity": "error",
    "detection": "config",
    "tags": [
      "widget",
      "control",
      "toolchain"
    ],
    "summary": "The Mobile Surfaces widget target lives outside the generated ios/ directory and is materialized by @bacons/apple-targets at prebuild time.",
    "symptom": "Hand-managed Xcode target gets wiped on the next prebuild, or the widget extension never appears in the built app.",
    "fix": "Keep the target source under apps/mobile/targets/widget/ with an expo-target.config.js. Pin @bacons/apple-targets at the supported exact version.",
    "docs": [
      "docs/architecture.md"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS027",
    "title": "Foreign Expo project must target iOS 17.2 or higher",
    "severity": "error",
    "detection": "config",
    "tags": [
      "ios-version",
      "config"
    ],
    "summary": "Same constraint as MS012, applied during an audit of an arbitrary Expo project that adopts Mobile Surfaces.",
    "symptom": "Audit fails with a deployment-target mismatch; a downstream prebuild surfaces compile errors on iOS 17.2-only symbols.",
    "fix": "Set ios.deploymentTarget to '17.2' (or higher) in app.json or via expo-build-properties.",
    "iosMin": "17.2",
    "docs": [
      "docs/compatibility.md"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS028",
    "title": "APNs auth key environment variables must be set before sending",
    "severity": "error",
    "detection": "runtime",
    "tags": [
      "push",
      "tokens"
    ],
    "summary": "Both the SDK and scripts/send-apns.mjs require APNS_KEY_ID, APNS_TEAM_ID, APNS_KEY_PATH, and APNS_BUNDLE_ID.",
    "symptom": "Throw at construction time (createPushClient) or at the first send. Often hidden inside a deployment whose env vars never made it into the runtime.",
    "fix": "Verify each env var on startup. The SDK's createPushClient validates presence; reject fast if any are missing.",
    "docs": [
      "docs/push.md#sdk-reference"
    ],
    "since": "1.0.0",
    "errorClasses": [
      "MissingApnsConfigError"
    ]
  },
  {
    "id": "MS029",
    "title": "Generated apps/mobile/ios/ is gitignored",
    "severity": "error",
    "detection": "config",
    "tags": [
      "cng",
      "config"
    ],
    "summary": "CNG-managed directories must not be checked into version control; commits will fight prebuild forever.",
    "symptom": "Pull request diffs include hundreds of lines under apps/mobile/ios/ that nobody intended to change. Reviewers cannot tell what is real.",
    "fix": "Add apps/mobile/ios/ to .gitignore. If files are already tracked, untrack with git rm -r --cached apps/mobile/ios then commit the .gitignore update.",
    "docs": [
      "docs/ios-environment.md"
    ],
    "since": "1.0.0"
  },
  {
    "id": "MS030",
    "title": "APNs provider token must be valid and current",
    "severity": "error",
    "detection": "runtime",
    "tags": [
      "push",
      "tokens"
    ],
    "summary": "APNs returns 403 with reason Forbidden, InvalidProviderToken, or ExpiredProviderToken when the auth-key JWT cannot be verified; each reason has a distinct operator response.",
    "symptom": "All sends fail with 403. ForbiddenError means the auth key was revoked in the Apple Developer portal. InvalidProviderTokenError means the JWT is malformed or signed with the wrong key id / team id. ExpiredProviderTokenError means the JWT is older than 60 minutes (typically clock skew, since the SDK refreshes at 50 minutes).",
    "fix": "ForbiddenError: mint a new auth key in the Apple Developer portal and update APNS_KEY_ID / APNS_KEY_PATH. InvalidProviderTokenError: verify APNS_KEY_ID matches the key file and APNS_TEAM_ID matches the developer account. ExpiredProviderTokenError: check system clock alignment against NTP; if the SDK is long-lived, confirm createPushClient is not being held past process restarts without re-minting.",
    "docs": [
      "docs/push.md#error-responses"
    ],
    "since": "2.1.0",
    "errorClasses": [
      "ExpiredProviderTokenError",
      "ForbiddenError",
      "InvalidProviderTokenError"
    ]
  }
] as const satisfies readonly TrapEntry[];

const trapsById: Record<string, TrapEntry> = Object.fromEntries(
  traps.map((entry) => [entry.id, entry]),
);

const trapsByErrorClass: Record<string, TrapEntry> = (() => {
  const out: Record<string, TrapEntry> = {};
  for (const entry of traps) {
    if (!entry.errorClasses) continue;
    for (const className of entry.errorClasses) {
      // Uniqueness is enforced by the catalog Zod schema, so the last-write
      // here would only happen if the catalog passed validation; this
      // re-check is redundant but cheap.
      out[className] = entry;
    }
  }
  return out;
})();

/**
 * Look up a trap by its catalog id (e.g. "MS018"). Returns undefined for
 * unknown ids.
 */
export function findTrap(id: string): TrapEntry | undefined {
  return trapsById[id];
}

/**
 * Look up a trap by the name of an error class that surfaces it (e.g.
 * "TopicDisallowedError"). Returns undefined for classes with no catalog
 * binding (most SDK self-correctness errors).
 */
export function findTrapByErrorClass(className: string): TrapEntry | undefined {
  return trapsByErrorClass[className];
}
